(()=>{
'use strict';
const PAGE_W=1240, PAGE_H=1754, PT_W=595.28, PT_H=841.89;
const COLORS={ink:'#0b1013',muted:'#747a7d',line:'#dedbd4',chip:'#efede8',navy:'#061323',paper:'#ffffff',soft:'#f7f5f1',gold:'#a4886a'};
const enc=new TextEncoder();
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const waitFonts=()=>document.fonts?.ready||Promise.resolve();
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function loadImage(url){return new Promise((resolve,reject)=>{const img=new Image();img.crossOrigin='anonymous';img.onload=()=>resolve(img);img.onerror=reject;img.src=url})}
async function safeImage(url){try{return await loadImage(url)}catch{try{const r=await fetch(url,{mode:'cors',cache:'no-store'});if(!r.ok)throw 0;const b=await r.blob(),u=URL.createObjectURL(b);const img=await loadImage(u);URL.revokeObjectURL(u);return img}catch{return null}}}
function roundRect(ctx,x,y,w,h,r,fill,stroke){r=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1.5;ctx.stroke()}}
function drawLine(ctx,x1,y1,x2,y2,color=COLORS.line,w=2){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.strokeStyle=color;ctx.lineWidth=w;ctx.stroke()}
function font(size,weight=400,family='IBM Plex Sans Arabic'){return `${weight} ${size}px "${family}", Arial, sans-serif`}
function wrap(ctx,text,maxWidth){const words=String(text||'').replace(/\s+/g,' ').trim().split(' ').filter(Boolean),lines=[];let line='';for(const word of words){const test=line?`${line} ${word}`:word;if(ctx.measureText(test).width<=maxWidth){line=test}else{if(line)lines.push(line);line=word}}if(line)lines.push(line);return lines}
function drawWrapped(ctx,text,x,y,maxWidth,lineHeight,opts={}){const {size=30,weight=400,color=COLORS.ink,align='right',direction='rtl',maxLines=Infinity,family='IBM Plex Sans Arabic'}=opts;ctx.font=font(size,weight,family);ctx.fillStyle=color;ctx.textAlign=align;ctx.textBaseline='alphabetic';ctx.direction=direction;const lines=wrap(ctx,text,maxWidth).slice(0,maxLines);for(let i=0;i<lines.length;i++)ctx.fillText(lines[i],x,y+i*lineHeight,maxWidth);return {lines,height:lines.length*lineHeight}}
function drawLogo(ctx,img,y=58,compact=false,lang='ar'){const x=72,s=compact?54:76;if(img){roundRect(ctx,x,y,s,s,15,COLORS.navy);ctx.save();roundRect(ctx,x,y,s,s,15);ctx.clip();ctx.drawImage(img,x,y,s,s);ctx.restore()}ctx.direction='ltr';ctx.textAlign='left';ctx.fillStyle=COLORS.ink;ctx.font=font(compact?34:48,600,'Cormorant Garamond');ctx.fillText('Dana',x+s+18,y+(compact?39:52));ctx.direction='rtl';ctx.textAlign='left';ctx.fillStyle=COLORS.gold;ctx.font=font(compact?16:20,400,lang==='ar'?'IBM Plex Sans Arabic':'Space Grotesk');ctx.fillText(lang==='ar'?'أعمال صحفية':'EDITORIAL NEWSROOM',x+s+20,y+(compact?58:78));}
function drawUserIcon(ctx,x,y){ctx.strokeStyle=COLORS.ink;ctx.lineWidth=2.5;ctx.beginPath();ctx.arc(x,y-10,8,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(x,y+14,15,Math.PI,0);ctx.stroke()}
function drawPin(ctx,x,y){ctx.strokeStyle=COLORS.ink;ctx.lineWidth=2.3;ctx.beginPath();ctx.arc(x,y-5,9,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(x-7,y+1);ctx.lineTo(x,y+17);ctx.lineTo(x+7,y+1);ctx.stroke()}
function drawCalendar(ctx,x,y){ctx.strokeStyle=COLORS.ink;ctx.lineWidth=2.2;ctx.strokeRect(x-12,y-13,24,23);drawLine(ctx,x-12,y-5,x+12,y-5,COLORS.ink,2);drawLine(ctx,x-6,y-17,x-6,y-10,COLORS.ink,2);drawLine(ctx,x+6,y-17,x+6,y-10,COLORS.ink,2)}
function drawClock(ctx,x,y){ctx.strokeStyle=COLORS.ink;ctx.lineWidth=2.2;ctx.beginPath();ctx.arc(x,y,13,0,Math.PI*2);ctx.stroke();drawLine(ctx,x,y,x,y-7,COLORS.ink,2);drawLine(ctx,x,y,x+6,y+4,COLORS.ink,2)}
function tagWidth(ctx,t){ctx.font=font(20,500);return ctx.measureText(t).width+42}
function drawFooter(ctx,qr,logo,url,lang,pageNo,total){const blackH=92,whiteH=142,whiteY=PAGE_H-blackH-whiteH,blackY=PAGE_H-blackH;ctx.fillStyle='#fff';ctx.fillRect(0,whiteY,PAGE_W,whiteH);drawLine(ctx,0,whiteY,PAGE_W,whiteY,'#ece9e3',1);if(qr){roundRect(ctx,58,whiteY+16,110,110,10,'#fff','#dedbd4');ctx.drawImage(qr,68,whiteY+26,90,90)}ctx.direction=lang==='ar'?'rtl':'ltr';ctx.textAlign=lang==='ar'?'left':'left';ctx.fillStyle=COLORS.ink;ctx.font=font(23,600,lang==='ar'?'IBM Plex Sans Arabic':'Space Grotesk');ctx.fillText(lang==='ar'?'امسح الكود لمتابعة المزيد':'Scan to read more',185,whiteY+55);ctx.fillStyle=COLORS.muted;ctx.font=font(17,400,lang==='ar'?'IBM Plex Sans Arabic':'Space Grotesk');ctx.fillText(lang==='ar'?'للاطلاع على المقال في موقع دانه بالجهر':'Open the original article on Dana Baljher',185,whiteY+88);ctx.direction='ltr';ctx.textAlign='left';ctx.font=font(12,400,'Space Grotesk');ctx.fillStyle='#8a8d8f';ctx.fillText(url,185,whiteY+113,790);ctx.fillStyle=COLORS.navy;ctx.fillRect(0,blackY,PAGE_W,blackH);if(logo)ctx.drawImage(logo,PAGE_W/2-27,blackY+18,54,54);ctx.fillStyle='#fff';ctx.textAlign='right';ctx.direction='rtl';ctx.font=font(16,400);if(lang==='ar'){ctx.direction='rtl';ctx.fillText('جدة، المملكة العربية السعودية',PAGE_W-64,blackY+37);ctx.fillText('جميع الحقوق محفوظة لدى دانه بالجهر',PAGE_W-64,blackY+64)}else{ctx.direction='ltr';ctx.fillText('Jeddah, Saudi Arabia',PAGE_W-64,blackY+37);ctx.fillText('All rights reserved · Dana Baljher',PAGE_W-64,blackY+64)}ctx.textAlign='left';ctx.direction='ltr';ctx.font=font(13,500,'Space Grotesk');ctx.fillStyle='#cfd5d8';ctx.fillText(`${pageNo} / ${total}`,62,blackY+54)}
function buildBodyLines(ctx,body,lang,maxW){const items=[];ctx.font=font(lang==='ar'?25:23,400,lang==='ar'?'IBM Plex Sans Arabic':'Space Grotesk');for(const para of body||[]){const lines=wrap(ctx,para,maxW);for(const line of lines)items.push({type:'line',text:line});items.push({type:'gap'})}return items}
function firstBodyStart(data,ctx){const rtl=data.lang==='ar',right=PAGE_W-86,titleSize=data.title.length>48?54:data.title.length>30?60:66;ctx.font=font(titleSize,700,rtl?'IBM Plex Sans Arabic':'Space Grotesk');const titleLines=wrap(ctx,data.title,PAGE_W-190).slice(0,3).length;ctx.font=font(26,400,rtl?'IBM Plex Sans Arabic':'Space Grotesk');const deckLines=wrap(ctx,data.excerpt||'',PAGE_W-190).slice(0,2).length;const deckY=415+titleLines*(titleSize*1.15)+28;const metaY=Math.max(645,deckY+Math.max(1,deckLines)*42+28);return metaY+205}
function splitIntoPages(data){const probe=document.createElement('canvas').getContext('2d');const maxW=PAGE_W-180;const items=buildBodyLines(probe,data.body,data.lang,maxW),pages=[];let first=true,i=0;while(i<items.length){const startY=first?firstBodyStart(data,probe):90,bottom=PAGE_H-92-142-48,lineH=data.lang==='ar'?47:42,gapH=24;const take=[];let y=startY;while(i<items.length){const it=items[i],h=it.type==='gap'?gapH:lineH;if(y+h>bottom&&take.length)break;take.push(it);y+=h;i++}pages.push({first,items:take,startY});first=false}if(!pages.length)pages.push({first:true,items:[],startY:900});return pages}
function drawFirstHeader(ctx,data,logo){drawLogo(ctx,logo,58,false,data.lang);drawLine(ctx,64,164,PAGE_W-64,164,'#e8e5df',2);const rtl=data.lang==='ar';ctx.direction=rtl?'rtl':'ltr';ctx.textAlign=rtl?'right':'left';const right=PAGE_W-86,left=86;if(data.seriesTitle){ctx.font=font(20,500);ctx.fillStyle=COLORS.ink;ctx.fillText(`${rtl?'من سلسلة:':'Series:'} ${data.seriesTitle}`,right,315);drawLine(ctx,right-35,300,right,300,COLORS.gold,2)}if(data.seriesIndex&&data.seriesTotal){roundRect(ctx,left,274,142,58,30,'#fff',COLORS.line);ctx.direction='ltr';ctx.textAlign='center';ctx.font=font(19,500,'Space Grotesk');ctx.fillStyle=COLORS.ink;ctx.fillText(`${data.seriesIndex} / ${data.seriesTotal}`,left+71,311)}const titleSize=data.title.length>48?54:data.title.length>30?60:66;const titleRes=drawWrapped(ctx,data.title,right,415,PAGE_W-190,titleSize*1.15,{size:titleSize,weight:700,color:COLORS.ink,align:rtl?'right':'left',direction:rtl?'rtl':'ltr',family:rtl?'IBM Plex Sans Arabic':'Space Grotesk',maxLines:3});const deckY=415+titleRes.height+28;drawWrapped(ctx,data.excerpt,right,deckY,PAGE_W-190,42,{size:26,weight:400,color:COLORS.muted,align:rtl?'right':'left',direction:rtl?'rtl':'ltr',family:rtl?'IBM Plex Sans Arabic':'Space Grotesk',maxLines:2});const metaY=Math.max(645,deckY+110);drawLine(ctx,80,metaY-42,PAGE_W-80,metaY-42,'#e8e5df',2);const entries=rtl?[['author',data.author],['place',data.place],['date',data.date],['time',data.readTime]]:[['time',data.readTime],['date',data.date],['place',data.place],['author',data.author]];const cellW=(PAGE_W-160)/4;entries.forEach((e,idx)=>{const cx=80+cellW*idx+cellW/2;if(idx)drawLine(ctx,80+cellW*idx,metaY-18,80+cellW*idx,metaY+42,'#e8e5df',2);const [type,val]=e;if(type==='author')drawUserIcon(ctx,cx-62,metaY+6);if(type==='place')drawPin(ctx,cx-55,metaY+4);if(type==='date')drawCalendar(ctx,cx-67,metaY+4);if(type==='time')drawClock(ctx,cx-72,metaY+4);ctx.textAlign='center';ctx.direction=rtl?'rtl':'ltr';ctx.fillStyle=COLORS.ink;ctx.font=font(18,600,rtl?'IBM Plex Sans Arabic':'Space Grotesk');ctx.fillText(val,cx+16,metaY+12)});drawLine(ctx,80,metaY+62,PAGE_W-80,metaY+62,'#e8e5df',2);const tagY=metaY+105;ctx.textAlign=rtl?'right':'left';ctx.direction=rtl?'rtl':'ltr';ctx.font=font(20,600,rtl?'IBM Plex Sans Arabic':'Space Grotesk');ctx.fillStyle=COLORS.ink;ctx.fillText(rtl?'الموضوعات':'Topics',right,tagY+27);let x=rtl?right-132:left+132;for(const t of (data.tags||[]).slice(0,6)){const w=tagWidth(ctx,t);if(rtl){x-=w;roundRect(ctx,x,tagY,w,44,23,COLORS.chip);ctx.fillStyle=COLORS.ink;ctx.font=font(17,500,rtl?'IBM Plex Sans Arabic':'Space Grotesk');ctx.textAlign='center';ctx.fillText(t,x+w/2,tagY+28);x-=10}else{roundRect(ctx,x,tagY,w,44,23,COLORS.chip);ctx.fillStyle=COLORS.ink;ctx.font=font(17,500,rtl?'IBM Plex Sans Arabic':'Space Grotesk');ctx.textAlign='center';ctx.fillText(t,x+w/2,tagY+28);x+=w+10}}drawLine(ctx,80,tagY+70,PAGE_W-80,tagY+70,'#e8e5df',1)}
function drawContinuationHeader(ctx,data,logo,pageNo){drawLogo(ctx,logo,42,true,data.lang);ctx.direction=data.lang==='ar'?'rtl':'ltr';ctx.textAlign=data.lang==='ar'?'right':'left';ctx.fillStyle=COLORS.muted;ctx.font=font(15,500);ctx.fillText(data.title,data.lang==='ar'?PAGE_W-70:230,81,PAGE_W-330);ctx.direction='ltr';ctx.textAlign='right';ctx.font=font(13,500,'Space Grotesk');ctx.fillText(String(pageNo).padStart(2,'0'),PAGE_W-68,56);drawLine(ctx,64,132,PAGE_W-64,132,'#e8e5df',2)}
function drawBody(ctx,data,page){const rtl=data.lang==='ar',x=rtl?PAGE_W-90:90,maxW=PAGE_W-180,lineH=rtl?47:42;ctx.direction=rtl?'rtl':'ltr';ctx.textAlign=rtl?'right':'left';ctx.fillStyle=COLORS.ink;ctx.font=font(rtl?25:23,400,rtl?'IBM Plex Sans Arabic':'Space Grotesk');let y=page.startY;for(const it of page.items){if(it.type==='gap'){y+=24;continue}ctx.fillText(it.text,x,y,maxW);y+=lineH}}
function makeCanvas(){const c=document.createElement('canvas');c.width=PAGE_W;c.height=PAGE_H;const ctx=c.getContext('2d',{alpha:false});ctx.fillStyle='#fff';ctx.fillRect(0,0,PAGE_W,PAGE_H);return [c,ctx]}
async function jpegBytes(canvas){const blob=await new Promise((res,rej)=>canvas.toBlob(b=>b?res(b):rej(new Error('JPEG encode failed')),'image/jpeg',0.94));return new Uint8Array(await blob.arrayBuffer())}
function buildPdf(jpegs){const chunks=[],offsets=[0];let pos=0;const pushAscii=s=>{const b=enc.encode(s);chunks.push(b);pos+=b.length};const pushBytes=b=>{chunks.push(b);pos+=b.length};pushAscii('%PDF-1.4\n%\xE2\xE3\xCF\xD3\n');const n=jpegs.length,objCount=2+n*3;function obj(id,body){offsets[id]=pos;pushAscii(`${id} 0 obj\n${body}\nendobj\n`)}obj(1,'<< /Type /Catalog /Pages 2 0 R >>');const kids=[];for(let i=0;i<n;i++)kids.push(`${3+i*3} 0 R`);obj(2,`<< /Type /Pages /Kids [${kids.join(' ')}] /Count ${n} >>`);for(let i=0;i<n;i++){const pageId=3+i*3,contentId=4+i*3,imageId=5+i*3,img=jpegs[i];obj(pageId,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PT_W} ${PT_H}] /Resources << /XObject << /Im0 ${imageId} 0 R >> >> /Contents ${contentId} 0 R >>`);const content=`q\n${PT_W} 0 0 ${PT_H} 0 0 cm\n/Im0 Do\nQ`;obj(contentId,`<< /Length ${enc.encode(content).length} >>\nstream\n${content}\nendstream`);offsets[imageId]=pos;pushAscii(`${imageId} 0 obj\n<< /Type /XObject /Subtype /Image /Width ${PAGE_W} /Height ${PAGE_H} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${img.length} >>\nstream\n`);pushBytes(img);pushAscii('\nendstream\nendobj\n')}const xref=pos;pushAscii(`xref\n0 ${objCount+1}\n0000000000 65535 f \n`);for(let id=1;id<=objCount;id++)pushAscii(`${String(offsets[id]).padStart(10,'0')} 00000 n \n`);pushAscii(`trailer\n<< /Size ${objCount+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`);const total=chunks.reduce((s,b)=>s+b.length,0),out=new Uint8Array(total);let at=0;for(const b of chunks){out.set(b,at);at+=b.length}return new Blob([out],{type:'application/pdf'})}
function safeName(s){return String(s||'Dana-Article').replace(/[\\/:*?"<>|]/g,'-').replace(/\s+/g,' ').trim().slice(0,100)}
async function exportArticle(data,button){if(!data?.title||!data?.body?.length)throw new Error('Article data is incomplete');const old=button?.innerHTML;if(button){button.disabled=true;button.innerHTML=data.lang==='ar'?'جارٍ تجهيز PDF…':'Preparing PDF…'}try{await waitFonts();await sleep(40);const [logo,qr]=await Promise.all([safeImage(data.logoUrl),safeImage(data.qrUrl)]);const pages=splitIntoPages(data),jpegs=[];for(let i=0;i<pages.length;i++){const [canvas,ctx]=makeCanvas();if(pages[i].first)drawFirstHeader(ctx,data,logo);drawBody(ctx,data,pages[i]);drawFooter(ctx,qr,logo,data.url,data.lang,i+1,pages.length);jpegs.push(await jpegBytes(canvas))}const blob=buildPdf(jpegs),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${safeName(data.title)} - Dana Baljher.pdf`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);return {pages:pages.length}}finally{if(button){button.disabled=false;button.innerHTML=old}}}
window.DanaPdf={exportArticle};
})();
