(() => {
  'use strict';
  const p = (text) => String(text).trim().split(/\n\s*\n/).map(x => x.trim()).filter(Boolean);

  const series = [{
    slug: 'what-reader-does-not-see',
    title: 'ما لا يراه القارئ',
    description: 'سلسلة مقالات تفتح ما يحدث قبل أن تصل المادة الصحفية إلى القارئ: كيف تُجمع المعلومات، وما الذي يُحذف أو يترجم أو يُعنون، وكيف يمكن لقرارات غير مرئية أن تغيّر ما يصل إليه.',
    title_en: "What the Reader Doesn't See",
    description_en: 'An essay series about the invisible decisions that shape a news story before it reaches the reader: how information is gathered, shortened, translated and framed, and how those choices can alter what ultimately arrives.',
    status: 'published',
    is_ongoing: true,
    featured: true
  }];

  const articles = [
    {
      slug: 'news-died-before-editor', type: 'article', typeLabel: 'مقال',
      title: 'الخبر الذي مات قبل أن يصل إلى المحرر', date: '2026-08-30', place: 'جدة', author: 'دانه بالجهر',
      image: 'assets/covers/default-article.svg', featured: false, pick: false,
      tags: ['ما لا يراه القارئ', 'غرف الأخبار', 'سير العمل', 'التحرير'],
      excerpt: 'بين وقوع الحدث وفتح المحرر للملف قد تمر ساعات كاملة لا تظهر في زمن إنتاج الخبر، بينما يكون جزء من عمره قد استُهلك قبل أن تبدأ الكتابة.',
      seriesSlug: 'what-reader-does-not-see', seriesOrder: 1,
      body: p(`
قد ينتهي اجتماع عند العاشرة صباحًا، ولا تصل مادته إلى المحرر إلا بعد الظهر. خلال تلك الساعات لم يكن الصحفي يكتب ببطء، ولم تكن غرفة الأخبار تراجع النص، وربما لم تعرف بوجود الخبر أصلًا. كانت التفاصيل لا تزال موزعة داخل المؤسسة، تنتظر أن تكتمل قبل أن تصبح جاهزة للتحرير. وحين يحدث ذلك أخيرًا، قد لا يحتاج تحرير الخبر إلى أكثر من عشر دقائق. في سجل الإنتاج تبدو هذه الدقائق زمن صناعة الخبر كله، بينما تختفي الساعات التي سبقتها من الحساب.

عمر الخبر لا يبدأ عندما يفتح المحرر الملف. قبل ذلك قد يكون ملخص الاجتماع وصل في مجموعة واتساب، والصور أُرسلت بالبريد الإلكتروني، وتصحيح أحد الأسماء جاء في رسالة خاصة، والصيغة النهائية لتصريح ما ظهرت في ملف جديد، بينما بقي رقم مهم داخل ملاحظة صوتية لم يسمعها الجميع. كل قناة تختصر زمن الإرسال بمفردها، غير أن كثرتها قد تجعل الوصول نفسه أكثر تعقيدًا؛ فالمطلوب لم يعد نقل التفاصيل فقط، بل معرفة أين توجد، وما الذي اكتمل منها، ومن ينتظر الخطوة التالية. ودراسة منشورة في دورية Digital Journalism، وهي دورية أكاديمية محكمة متخصصة في الصحافة الرقمية، اعتمدت سبعة أشهر من العمل الإثنوغرافي داخل غرفتي أخبار في تشيلي، وأظهرت أن استخدام واتساب أثر في علاقة الصحفيين بالمصادر، وطريقة حصولهم على المعلومات، وإيقاع العمل اليومي. التقنية قرّبت الأشخاص من بعضهم، من دون أن تنشئ بالضرورة مسارًا واحدًا لما يتبادلونه.

يظهر أثر هذا التشتت عندما تبدأ النسخ بالتكاثر. ملف عند المحرر، وآخر لدى المسؤول الذي راجعه، وثالث وصل إلى المصمم قبل آخر تعديل. عندها لا يعود السؤال: أين الخبر؟ بل: أي خبر؟ قد تكون كل نسخة صحيحة لحظة إرسالها، ثم يجعل تغيير رقم أو اسم أو تصريح واحدة منها فقط صالحة للنشر. وإذا كان تحديد النسخة المعتمدة يتوقف على عبارة «أرسل لي آخر نسخة»، فقد أصبح جزء من سلامة العمل محفوظًا في ذاكرة الأشخاص وصناديق رسائلهم بدل أن يكون معلومًا للجميع.

الأعمق أن تسلسل الورود نفسه قد يدخل إلى النص. تصريح يأتي مبكرًا يمكن أن يرسم للمحرر البنية الأولية للمادة، ثم تأتي معلومة أهم بعدما تشكلت زاوية مبدئية، فتُعامل بوصفها إضافة مع أنها ربما كانت ستتصدر الخبر لو حضرت منذ البداية. ويقترب ذلك مما يعرف في علم النفس بـ«أثر الأسبقية»، أي ميل المعلومات المقدمة أولًا إلى أن تحظى بحضور أقوى في الذاكرة وقد تؤثر في التقييمات اللاحقة. لا يعني ذلك أن الأسبقية تحسم قرار المحرر، لكنها توضح لماذا لا يكون تسلسل المدخلات محايدًا دائمًا، ولماذا يصبح تدفق المعلومات جزءًا من العملية التحريرية نفسها.

من هنا تبدو بعض مقاييس السرعة ناقصة. تستطيع المؤسسة أن تعرف متى بدأ التحرير، وكم استغرقت المراجعة، وفي أي ساعة خرج النص، بينما يبقى مجهولًا الزمن الذي مضى بين وقوع الحدث واكتمال مادته داخلها. فإذا بدأ الحساب من لحظة دخول أول معلومة، لا من لحظة وصول الملف إلى الصحفي، ظهرت مرحلة كاملة كانت خارج القياس. عندها يصبح زمن الانتقال بين المراحل نفسه مؤشرًا للأداء، لا المدة التي يقضيها الصحفي في الكتابة وحدها.

معالجة هذا الخلل لا تحتاج قناة جديدة تضاف إلى القنوات القديمة، بل مرجعًا واحدًا يرافق الخبر منذ بدايته. ولهذا المبدأ أصل في البنية التقنية لصناعة الأخبار. فـNewsML-G2 معيار مفتوح لتبادل المحتوى الإخباري وبياناته، صادر عن المجلس الدولي للاتصالات الصحفية (IPTC)، الذي يطور مواصفات تقنية لقطاع الأخبار. ويشترط لكل عنصر إخباري معرّفًا ينبغي أن يظل فريدًا عالميًا ومستقلًا عن مكان وجود المادة، ويدعم ترقيم الإصدارات عند تحديث المحتوى، كما يتضمن عنصرًا للتخطيط يتيح متابعة ما خُطط لتغطيته وما أُنجز منه. الفكرة أن تظل هوية الخبر معروفة وهو ينتقل بين الأنظمة والمراحل، بدل أن يصبح كل ملف جديد كيانًا منفصلًا عن سابقه.

وفي التطبيق الداخلي يمكن ترجمة ذلك إلى سجل مركزي يُفتح منذ ورود أول معلومة عن الحدث: رقم مرجعي ثابت، المصدر، وقت الورود، العناصر المتوافرة والناقصة، المسؤول الحالي، وحالة المادة. النص والصور والتصريحات لا تتنقل كنسخ متنافسة، بل ترتبط بالمادة ذاتها، ويُحفظ تاريخ التعديل ومن أجراه. وتقدم منصة Superdesk المفتوحة المصدر لإدارة غرف الأخبار مثالًا عمليًا على هذا المنطق؛ إذ تسمح باستقبال المحتوى من مصادر مختلفة وتحريكه عبر مراحل قابلة للتخصيص مثل الوارد والعمل والموافقة والنشر، مع بقاء سير الإنتاج مرئيًا داخل النظام.

هذه المركزية لا تعني إنشاء بوابة جديدة ينتظر عندها الجميع. يستطيع فرع أن يضيف صورة، وإدارة أخرى أن تستكمل رقمًا، والمتحدث أن يعتمد اقتباسًا، بينما يبدأ الصحفي بما تأكد بالفعل. حتى المادة العاجلة يمكن أن تتحرك وهي مصنفة بوضوح على أنها غير مكتملة، مع بيان ما ينقصها ومن يتولى استكماله. الفرق أن النقص يصبح معلومًا، وتصبح مسؤولية استكماله محددة، بدل أن يكتشفه المحرر بالصدفة عندما يصل إلى موضع فارغ في القصة.

بعد ذلك تتحول بيانات المسار من توثيق داخلي إلى أداة تشخيص. إذا كانت عشرات الأخبار تتوقف في النقطة نفسها، فالمشكلة لم تعد حادثة فردية. تأخر الصور باستمرار يشير إلى خلل في طريقة جمعها، وكثرة المواد المنتظرة عند مستوى اعتماد واحد قد تستدعي مراجعة توزيع الصلاحيات، ومرور خبر روتيني بالطريق نفسه الذي تمر به مادة حساسة يعني أن المؤسسة تعامل درجات مختلفة من المخاطر بالإجراء ذاته. عندها يمكن إصلاح المسار الذي يصنع الاختناق، بدل مطالبة كل شخص في نهايته بأن يعمل أسرع. ويضيف التتبع فائدة أخرى: أصل الرقم، ومصدر الصورة، وتاريخ التعديل، وصاحب الموافقة لا تعود تفاصيل موزعة في محادثات قديمة؛ تصبح جزءًا من ذاكرة المؤسسة نفسها.

حين يصل الخبر إلى المحرر، يبدأ الجزء المرئي من صناعته تقريبًا، بينما تكون مراحل سابقة قد استهلكت من وقته من دون أن تظهر في النسخة المنشورة. وبين الحدث والسطر الأول رحلة قد تحدد متى يخرج الخبر، وأي نسخة تعتمد، وأي معلومة تتصدره. أحيانًا لا يموت الخبر على مكتب الصحفي؛ يصل إليه وقد فُقد جزء من عمره قبل أن تبدأ الكتابة.
      `),
      en: {
        title: 'The Story That Died Before It Reached the Editor',
        excerpt: 'Between an event taking place and an editor opening the file, hours may pass that never appear in production time—while part of the story’s useful life has already been spent.',
        place: 'Jeddah', tags: ['What the Reader Does Not See','Newsrooms','Workflow','Editing'],
        body: p(`
A meeting may end at ten in the morning, yet its material may not reach the editor until the afternoon. During those hours the journalist was not writing slowly, the newsroom was not reviewing the copy, and it may not even have known that the story existed. The details were still scattered across the institution, waiting to become complete enough to edit. When that finally happens, writing the story may take no more than ten minutes. In the production log, those minutes look like the entire life of the story, while the hours that came before them disappear from the calculation.

The life of a story does not begin when the editor opens the file. Before that, a meeting summary may have arrived in a WhatsApp group, photographs by email, a correction to a name in a private message, and the final wording of a statement in a new document, while an important number remains inside a voice note that not everyone has heard. Each channel may shorten transmission time on its own, yet the multiplication of channels can make access itself more complicated. The task is no longer simply to move details, but to know where they are, what has been completed, and who is waiting for the next step. A study published in Digital Journalism, a peer-reviewed academic journal specializing in digital journalism, drew on seven months of ethnographic work in two Chilean newsrooms and found that WhatsApp affected journalists’ relationships with sources, how they obtained information, and the rhythm of daily work. Technology brought people closer together without necessarily creating a single path for what they exchanged.

The effect of that fragmentation becomes visible when versions begin to multiply. One file sits with the editor, another with the manager who reviewed it, and a third has already reached the designer before the latest amendment. The question is no longer “Where is the story?” but “Which story?” Every version may have been correct at the moment it was sent, until a changed number, name or quote makes only one of them fit for publication. If identifying the approved version depends on someone saying “send me the latest copy,” part of the safety of the workflow has been stored in people’s memories and inboxes instead of being visible to everyone.

More deeply, the order in which information arrives can enter the text itself. A statement that arrives early may give the editor an initial structure, then a more important fact appears after a preliminary angle has already formed and is treated as an addition, even though it might have led the story had it been present from the start. This approaches what psychology calls the “primacy effect”: the tendency for information presented first to have a stronger presence in memory and potentially influence later judgments. Primacy does not determine an editor’s decision, but it helps explain why the sequence of inputs is not always neutral and why information flow itself becomes part of the editorial process.

From this perspective, some measures of speed are incomplete. An organization may know when editing began, how long review took, and the hour at which the text was published, while remaining unable to see how much time passed between the event and the point at which its material became complete inside the organization. If measurement begins when the first piece of information enters the system rather than when the file reaches the journalist, an entire stage that had been outside the metric becomes visible. The time spent moving between stages then becomes a performance indicator in its own right, not merely the time a journalist spends writing.

Fixing this does not require adding another channel to the old ones. It requires a single reference that accompanies the story from the beginning. That principle already has a technical foundation in news production. NewsML-G2 is an open standard for exchanging news content and metadata issued by the International Press Telecommunications Council (IPTC), which develops technical specifications for the news industry. It requires each news item to have an identifier that remains globally unique and independent of where the content is stored, supports version numbering when content is updated, and includes planning elements that can track what was intended for coverage and what has been completed. The idea is to preserve the identity of a story as it moves across systems and stages instead of allowing every new file to become a separate object from the one before it.

Internally, that logic can become a central record opened as soon as the first information about an event arrives: a fixed reference number, source, arrival time, available and missing elements, current owner, and status. Text, images and quotes do not travel as competing copies; they are attached to the same item, with a history of changes and who made them. The open-source newsroom management platform Superdesk offers a practical example of this model by allowing content from different sources to move through configurable stages such as ingest, work, approval and publishing while keeping the production flow visible inside one system.

Centralization does not mean creating another gate at which everyone must wait. One branch can add a photograph, another department can complete a number, and a spokesperson can approve a quote while the journalist begins with what has already been verified. Even breaking material can move forward while clearly marked as incomplete, with a visible account of what is missing and who is responsible for supplying it. The difference is that the gap becomes known and ownership of it becomes explicit instead of being discovered by chance when the editor reaches an empty place in the story.

The workflow data can then move from internal documentation to diagnosis. If dozens of stories repeatedly stop at the same point, the problem is no longer an isolated incident. Consistent delays in photographs point to a weakness in how they are collected. A pile-up of stories at a single approval level may require a review of authority distribution. A routine story taking the same path as a highly sensitive one means the organization is applying one procedure to very different levels of risk. The workflow creating the bottleneck can then be repaired instead of asking everyone at the end of it to work faster. Tracking adds another benefit: the origin of a number, the source of an image, the date of an amendment and the person who approved it stop being fragments scattered across old conversations and become part of institutional memory.

By the time a story reaches the editor, the visible part of its production is only beginning, while earlier stages may already have consumed part of its useful life without appearing in the published version. Between the event and the first line lies a journey that can determine when the story is released, which version is used and which fact leads. Sometimes a story does not die on the journalist’s desk; it arrives there after part of its life has already been lost.
        `)
      }
    },
    {
      slug: 'two-hours-four-lines', type: 'article', typeLabel: 'مقال',
      title: 'ساعتان من الكلام اختفتا في أربعة أسطر', date: '2026-08-30', place: 'جدة', author: 'دانه بالجهر',
      image: 'assets/covers/default-article.svg', featured: false, pick: false,
      tags: ['ما لا يراه القارئ', 'الاختصار', 'القيم الخبرية', 'التحرير'],
      excerpt: 'لا توجد صحافة بلا حذف، لكن اختصار عشرات التفاصيل إلى أربعة أسطر لا يغيّر الحجم فقط؛ بل يغيّر الصورة التي سيعرف بها القارئ الحدث.',
      seriesSlug: 'what-reader-does-not-see', seriesOrder: 2,
      body: p(`
قد يستمر اجتماع ساعتين، يتحدث خلالهما أكثر من مسؤول، وتظهر أرقام ومواعيد وقرارات واعتراضات وتفاصيل تنفيذية، ثم يخرج منه خبر من أربعة أسطر. القارئ سيرى النتيجة فقط؛ لن يعرف كم معلومة كانت أمام الصحفي، ولا أيها بقي، ولا أيها خرج من النص قبل أن يراه.

لا توجد صحافة بلا حذف. نقل كل ما قيل سيحوّل الخبر إلى محضر، والإبقاء على كل رقم سيجعل الأهم يضيع وسط التفاصيل. لذلك لا تكمن المشكلة في أن الصحفي اختصر، بل في أن الاختصار نفسه قرار تحريري لا يظهر للقارئ. حين تُختصر عشرون معلومة إلى أربع، لا يتغير الحجم فقط؛ تتغير الصورة التي سيعرف بها القارئ الحدث. وليس المطلوب أن تعكس مساحة النص الزمن الذي استغرقه كل نقاش؛ فقد تكون جملة واحدة أهم من ساعة كاملة. المسألة أن الانتقال من عشرات التفاصيل إلى عدد قليل منها يمنح ما بقي وزنًا أكبر، ويجعل ما استُبعد جزءًا من صناعة المعنى أيضًا.

تفسر القيم الخبرية جزءًا من هذه العملية. ففي دراسة منشورة في دورية Journalism Studies، وهي دورية أكاديمية محكّمة متخصصة في دراسات الصحافة، حلل الباحثان توني هاركَب وديردري أونيل 711 قصة اختارتها صحف بريطانية لتكون القصص الرئيسية في صفحات الأخبار، وأعادا من خلالها فحص العوامل المرتبطة بالاختيار الصحفي. وظهرت بينها الصلة بالجمهور، والمفاجأة، والصراع، وحجم الحدث، والشخصيات البارزة، وأجندة المؤسسة الإعلامية. الدراسة تتعامل مع الاختيار على نطاق أوسع، لا مع انتقاء جملة بعينها من اجتماع؛ لذلك لا تخبرنا كيف سيقرر محرر فردي، لكنها توضح أن «الأهمية» ليست معيارًا منفردًا يفسر ما يدخل الخبر وما يبقى خارجه.

ويظهر ذلك داخل الحدث الواحد. قد يلقي مسؤول عبارة قوية تصلح للاقتباس، ثم يذكر بعد دقائق تعديلًا إجرائيًا صغيرًا قد يغيّر الخدمة لمئات الأشخاص. الأولى جاهزة لغويًا؛ لها متحدث واضح وجملة مكتملة ويمكن نقلها فورًا. الثانية تحتاج إلى تفكيك: ما الذي تغير؟ متى يبدأ؟ من يشمله؟ وكيف يختلف عما كان قائمًا؟ وتحت ضغط العمل قد لا تتنافس المعلومتان على الأهمية وحدها؛ فقد تدخل سهولة صياغة كل منهما ضمن ما يرجح حضور إحداهما في النص. وهكذا قد يخرج القارئ وهو يعرف التصريح الأشهر ولا يعرف موعد تطبيق القرار، من دون أن تكون في النص معلومة مختلقة واحدة. ما تغير هو ميزان ما بقي وما خرج.

لهذا لا تكفي مراجعة النص بسؤال: «هل كل جملة صحيحة؟». جمعية الصحفيين المحترفين SPJ، وهي منظمة مهنية أمريكية معنية بأخلاقيات الصحافة، تحذر في مدونتها من التشويه أو التبسيط المخل عند تلخيص القصة. وهذه نقطة مختلفة عن الخطأ المباشر: فقد تكون الجمل المنشورة صحيحة واحدةً واحدة، بينما يجعل الاختصار صورة الحدث أضيق مما تسمح به مادته الأصلية.

زيادة عدد الكلمات لن تحل المشكلة. فقد يهمل خبر من ثمانمئة كلمة التفصيل الحاسم كما قد يهمله خبر من مئتين، لأن الخلل يمكن أن يحدث قبل كتابة السطر الأول. والصحفي الذي يعود من اجتماع طويل ومعه صفحات متفرقة من الملاحظات، وما بقي في ذاكرته مما لفت انتباهه، يكون قد بدأ الحذف قبل أن يرى المادة كلها أمامه. ما لم يُدوّن جيدًا لا يدخل المنافسة أصلًا، وما لم يُلتقط في اللحظة المناسبة قد يصبح كأنه لم يُقل.

أدوات التفريغ الآلي تستطيع هنا معالجة جزء محدد من المشكلة: أن تمنح الصحفي إمكانية العودة إلى ما قيل بدل الاعتماد على الذاكرة وحدها. وهذا ليس استخدامًا افتراضيًا بعيدًا عن غرف الأخبار؛ ففي دراسة لمعهد رويترز لدراسة الصحافة شملت 1004 صحفيين في المملكة المتحدة، كان التفريغ وإنتاج النصوص المصاحبة أكثر استخدامات الذكاء الاصطناعي شيوعًا بينهم، إذ قال 49% إنهم يستخدمونه لهذا الغرض مرة شهريًا على الأقل. كما تسمح المعايير المحدثة لوكالة أسوشيتد برس، وهي وكالة أنباء أمريكية دولية، باستخدام الذكاء الاصطناعي للمساعدة في التفريغ، لكنها تبقي الحكم التحريري والتحقق والمسؤولية في يد الصحفي.

وهذا الحد الفاصل مهم. تحويل ساعتين من الصوت إلى عشرات الصفحات لا يخبر الصحفي بما ينبغي نشره؛ هو فقط يقلل احتمال أن يتخذ قرار الحذف قبل أن يعرف كل ما يملكه. الخطوة التي تلي التفريغ أهم: أن تتحول المادة قبل الكتابة إلى خريطة لما أنتجه الحدث فعلًا. لا قائمة بكل جملة، بل جرد للعناصر التي تستحق المفاضلة: ما القرار الجديد؟ ما الذي تغير عن السابق؟ ما الرقم الذي يضيف معرفة؟ متى يبدأ التنفيذ؟ من يتأثر؟ ما التعهد الذي يمكن الرجوع إليه لاحقًا؟ وما المسألة التي بقيت بلا جواب؟

عندها يبدأ الاختصار بعد اكتمال الرؤية، لا قبلها. يستطيع المحرر أن يحذف معظم الخريطة ويبقي أربعة أسطر فقط، لكن الأربعة خرجت هذه المرة من عناصر شوهدت وقورنت، لا من بضعة أشياء نجحت في الوصول إلى الملاحظات. ولا تحتاج غرفة الأخبار إلى توثيق سبب حذف كل تفصيل؛ يكفي أن تتوقف عند ما يمكن لغيابه أن يغيّر فهم القارئ، وتسأل إن كان استبعاده قرارًا تحريريًا مقصودًا أم نتيجة أنه ضاع وسط كمية الكلام.

وتظهر المشكلة المؤسسية عندما تُراجع دوريًا عينة من هذه المواد، لا خبرًا واحدًا فقط. فإذا ظهر أن نوعًا بعينه من المعلومات يفقد مكانه باستمرار أمام عناصر أخرى، فالمؤسسة لا تكتشف سهوًا منفردًا؛ تكتشف نمطًا في طريقة صناعة الأولوية. عندها يتحول السؤال من «من نسي هذه المعلومة؟» إلى «لماذا يخسر هذا النوع من المعلومات مكانه كل مرة؟». وهنا تصبح مراجعة الحذف وسيلة لفحص طريقة رؤية غرفة الأخبار للحدث، لا لتدقيق النص بعد انتهائه فقط.

القارئ لن يرى الساعتين، ولا المادة الكاملة التي صُنع منها الخبر، ولا العناصر التي تنافست على أربعة أسطر. لذلك فإن المسؤولية لا تقتصر على اختيار معلومات صحيحة، بل تمتد إلى التأكد من أن ما اختفى لم يكن أهم مما بقي. فالحذف ضرورة صحفية، لكنه يصبح قرارًا يستحق المراجعة حين يمكن لما استُبعد أن يغيّر ما يفهمه القارئ عن الحدث.
      `),
      en: {
        title: 'Two Hours of Talk Disappeared into Four Lines',
        excerpt: 'Journalism cannot exist without omission, but reducing dozens of details to four lines does more than change length: it changes the picture through which the reader will know the event.',
        place: 'Jeddah', tags: ['What the Reader Does Not See','Condensation','News values','Editing'],
        body: p(`
A meeting may last two hours. Several officials speak, figures and dates appear, decisions are announced, objections are raised and implementation details emerge—then the resulting news story is four lines long. The reader sees only the result. They do not know how much information the journalist had in front of them, which elements remained, or which left the text before it was ever seen.

There is no journalism without omission. Reproducing everything that was said would turn a news story into minutes of a meeting, while keeping every number would bury the most important information inside detail. The problem, then, is not that a journalist shortened the material. It is that shortening is itself an editorial decision that remains invisible to the reader. When twenty pieces of information become four, size is not the only thing that changes; the picture through which the reader knows the event changes as well. The length of the text does not need to mirror the time spent on each discussion—a single sentence may be more important than an hour of conversation. The point is that moving from dozens of details to a small number gives greater weight to what survives and makes what was excluded part of meaning-making too.

News values explain part of that process. In a study published in Journalism Studies, a peer-reviewed journal devoted to journalism research, Tony Harcup and Deirdre O’Neill analyzed 711 stories selected by British newspapers as lead news stories and re-examined the factors associated with journalistic selection. Among them were relevance to audiences, surprise, conflict, the scale of an event, prominent people and the agenda of the news organization. The study examines selection at a broader level rather than the choice of a single sentence from a meeting, so it cannot tell us how an individual editor will decide. It does show, however, that “importance” is not a single criterion capable of explaining what enters a story and what remains outside it.

That becomes visible inside a single event. An official may deliver a forceful, quotable line and, minutes later, mention a small procedural change that could alter a service for hundreds of people. The first is linguistically ready: it has a clear speaker, a complete sentence and can be transferred immediately. The second has to be unpacked. What changed? When does it begin? Who is affected? How is it different from what existed before? Under pressure, the two pieces of information may not compete on importance alone; how easy each is to write can also influence which one finds its way into the text. A reader may therefore leave knowing the most memorable statement but not when the decision takes effect, even though the story contains no invented fact. What changed was the balance between what remained and what disappeared.

That is why reviewing a story with only one question—“Is every sentence true?”—is not enough. The Society of Professional Journalists (SPJ), a U.S. professional organization concerned with journalism ethics, warns in its code against distortion or oversimplification when summarizing a story. This is different from a direct factual error. Every published sentence may be individually correct while the compression makes the event look narrower than the original material supports.

Adding words does not solve the problem. An 800-word story can omit the decisive detail just as a 200-word one can, because the failure may occur before the first sentence is written. A journalist returning from a long meeting with scattered pages of notes and whatever remained in memory has already begun to omit material before seeing the whole event laid out in front of them. What was not recorded well does not enter the competition at all, and what was not captured at the right moment can become as though it was never said.

Automated transcription can address one specific part of this problem: it can give the journalist a way to return to what was said instead of relying on memory alone. This is not a hypothetical use far removed from newsrooms. In a Reuters Institute for the Study of Journalism survey of 1,004 journalists in the United Kingdom, transcription and caption generation were the most common uses of AI, with 49% saying they used it for that purpose at least monthly. Updated Associated Press standards also allow AI to assist with transcription while keeping editorial judgment, verification and responsibility with the journalist.

That boundary matters. Turning two hours of audio into dozens of pages does not tell a journalist what should be published. It only reduces the chance that the decision to omit will be made before the journalist knows what they actually have. The step after transcription is more important: before writing, the material becomes a map of what the event produced. Not a list of every sentence, but an inventory of the elements worth comparing. What is the new decision? What changed from before? Which number adds knowledge? When does implementation begin? Who is affected? Which commitment can be checked later? What question remains unanswered?

Condensation then begins after the field of view is complete rather than before it. An editor may still remove most of the map and keep only four lines, but those four now emerged from elements that were seen and compared rather than from the few things that happened to make it into the notes. A newsroom does not need to document a reason for excluding every detail. It needs to pause over what could change the reader’s understanding if absent and ask whether the omission was a deliberate editorial choice or simply the result of the information being lost inside the volume of material.

The institutional problem appears when samples of such stories are reviewed periodically rather than treating each case in isolation. If one type of information repeatedly loses its place to other elements, the organization is not discovering a one-off oversight; it is discovering a pattern in the way priority is produced. The question changes from “Who forgot this fact?” to “Why does this type of information lose its place every time?” Reviewing omission then becomes a way to examine how the newsroom sees an event, not merely a way to proofread the text after it is finished.

The reader will never see the two hours, the complete material from which the story was made, or the elements that competed for four lines. Responsibility therefore extends beyond choosing accurate facts. It includes making sure that what disappeared was not more important than what remained. Omission is a journalistic necessity, but it becomes a decision that deserves scrutiny when what was excluded could change what the reader understands about the event.
        `)
      }
    },
    {
      slug: 'three-languages-three-truths', type: 'article', typeLabel: 'مقال',
      title: 'ثلاث لغات صنعت ثلاث حقائق', date: '2026-08-30', place: 'جدة', author: 'دانه بالجهر',
      image: 'assets/covers/default-article.svg', featured: false, pick: false,
      tags: ['ما لا يراه القارئ', 'الترجمة الصحفية', 'اللغات', 'الدقة'],
      excerpt: 'قد تنشر المؤسسة الخبر نفسه بثلاث لغات، لكن اختلافًا صغيرًا في درجة اليقين أو قوة الفعل قد يجعل القراء يصلون إلى ثلاث نسخ مختلفة من الموقف نفسه.',
      seriesSlug: 'what-reader-does-not-see', seriesOrder: 3,
      body: p(`
قد تنشر مؤسسة الخبر نفسه بالعربية والإنجليزية والفرنسية في اللحظة ذاتها. الحدث والصورة والأسماء لم تتغير، وحتى عدد الفقرات قد يكون متقاربًا. ومع ذلك قد يقرأ المتلقي العربي أن جهة ما «دعت» إلى إجراء، بينما يفهم القارئ في لغة أخرى أنها «حثّت» عليه، ويجد ثالث صياغة توحي بأن الموقف أكثر حسمًا مما كان في الأصل. لا يحتاج الاختلاف إلى خطأ فادح كي يصنع أثرًا؛ أحيانًا تكفي كلمة صحيحة في القاموس، لكنها ليست الكلمة التي تحمل القوة نفسها في سياقها.

لهذا لا تعمل الترجمة الصحفية كآلة تستبدل مفردة بأخرى. فالخبر حين يُترجم يعبر إلى نظام لغوي جديد له طرائقه في التعبير عن اليقين والاحتمال، والمسؤولية، والالتزام، والمسافة بين المتحدث وما يقوله. فليست commitment وpledge متطابقتين في كل سياق، كما لا تحمل urge وrequest بالضرورة الدرجة نفسها من الإلحاح. وقد يبدو الفارق صغيرًا عند البحث عن مقابل عربي، لكنه يصبح مهمًا حين يغيّر مقدار اليقين، أو قوة الطلب، أو درجة تبنّي المتحدث للموقف. هنا لا يعود السؤال: هل الترجمة مفهومة؟ بل: هل وصل المعنى إلى قارئ اللغة الثانية بالقوة الدلالية نفسها التي كان عليها في الأصل؟

دراسة منشورة في دورية Journalism، وهي دورية أكاديمية محكّمة متخصصة في دراسات الصحافة، استندت إلى مقابلات معمقة أجرتها الباحثة أليشيا رايت مع صحفيين هنود في نيودلهي خلال عامي 2018 و2019، ودرست كيف يتعاملون مع الانتقال من مقابلة منطوقة بالهندية إلى مادة مكتوبة بالإنجليزية. وأظهرت أن الصحفي لا ينقل الكلمات فقط؛ بل يتعامل مع ما يجد له مقابلًا واضحًا وما لا ينتقل بسهولة إلى اللغة الأخرى، ويعيد تقديم المادة لجمهور لغوي جديد، فيمكن للمعنى خلال انتقاله من المصدر إلى القارئ أن يكتسب دلالات لم تكن حاضرة بالدرجة نفسها في اللغة الأولى. ويعزز بحث آخر منشور في Journalism Studies عام 2024 هذه الطبيعة التحريرية للترجمة؛ إذ درس خدمة United News of India باللغة الأردية، وخلص إلى أن «ترجمة الأخبار» مكوّن مهم، وإن كان محل جدل، من العمل الإعلامي داخل صحافة اللغات الهندية.

وتصبح هذه الفروق أكثر حساسية في الأخبار الدبلوماسية والقانونية. فالموقف المعلن ليس تعهدًا، والتعهد ليس قرارًا ملزمًا، كما أن الاسم الرسمي لهيئة أو وضع قانوني ليس مجرد تسمية يمكن استبدالها بما يبدو قريبًا لغويًا. إذا سُوّيت هذه الدرجات أثناء الانتقال بين اللغات، قد تبقى الوقائع الأساسية صحيحة بينما يتغير ما تعنيه. عندها لا تنشر المؤسسة ثلاث أكاذيب، بل ثلاث نسخ متفاوتة من موقف كان يفترض أن يكون واحدًا.

الاقتباس أكثر حساسية، لأن القارئ يفترض أنه أقرب أجزاء الخبر إلى صوت صاحبه. معايير رويترز الصحفية تنص على أن ترجمة الاقتباسات ينبغي أن تكون طبيعية في اللغة الجديدة من دون الوقوع في الحرفية الجامدة، لكن مع الحفاظ على نبرة الأصل. وتحذر الوكالة تحديدًا من إعادة ترجمة اقتباس إلى لغته الأولى بعدما مر عبر وسيلة أخرى بلغة مختلفة، لأن النتيجة قد تصبح بعيدة عمّا قيل أصلًا. الحرفية ليست ضمانًا للدقة، والطلاقة ليست ضمانًا لها أيضًا؛ المطلوب أن تتغير الصياغة بالقدر الذي تحتاجه اللغة، من دون أن تتغير نبرة المتحدث أو دلالة كلامه.

وتزداد المسافة عندما لا يترجم المحرر من المصدر نفسه. تصريح قيل بالعربية قد تنقله جهة بالإنجليزية، ثم تعتمد غرفة أخبار النسخة الإنجليزية لإنتاج خبر بالفرنسية أو العربية من جديد. كل مرحلة تبدو معقولة منفردة، لكن السلسلة تضيف وسيطًا جديدًا بين القارئ والكلام الأصلي. وإذا اختفى الأصل من أمام المحرر، يصعب عليه معرفة إن كانت العبارة التي أمامه اختيار المتحدث أم اختيار المترجم السابق. عندها لا تنتقل الترجمة فقط بين اللغات؛ تنتقل معها قرارات تحريرية لا يعرف اللاحقون أين بدأت.

وليس الذكاء الاصطناعي أصل هذه المشكلة. يمكن لمترجم بشري متمكن أن يختار مقابلًا غير مناسب لسياق مؤسسي، كما تستطيع أداة آلية أن تنتج جملة سليمة لغويًا وتُسقط فارقًا دقيقًا بين مفهومين. المؤسسات التي تتعامل يوميًا مع نصوص حساسة لا تعتمد لذلك على المعرفة اللغوية الفردية وحدها. فالأمم المتحدة تستخدم قاعدة UNTERM للمصطلحات الرسمية، إلى جانب أدوات للترجمة بمساعدة الحاسوب ومواءمة النصوص ومستودعات الوثائق. ويبحث مترجموها ومحرروها في المصطلحات الجديدة، ويتحققون منها بالرجوع إلى مصادر موثوقة وبالتشاور مع المختصين قبل تخزين المعتمد منها. الأدوات هنا تدعم الاتساق والدقة، لكنها لا تلغي الحاجة إلى حكم بشري قادر على فهم الدلالة والنبرة وحتى الغموض المقصود في بعض النصوص الدبلوماسية.

ويمكن لغرفة الأخبار استعارة هذا المنطق من دون أن تتحول إلى إدارة ترجمة دولية. بدل أن يبدأ كل محرر من قاموسه وذاكرته، تبني المؤسسة قاموسًا تحريريًا حيًا للمصطلحات المتكررة في تغطيتها: الأصل، والمقابل المعتمد في كل لغة، والسياق الذي يصلح فيه، والمصدر الرسمي للمسميات القانونية والمؤسسية، والتنبيه إلى البدائل التي تبدو متقاربة لكنها تغير الدلالة. وكلما ظهر استخدام جديد أو تغير مسمى رسمي، يُراجع السجل نفسه بدل أن تبدأ كل ترجمة من الصفر.

غير أن توحيد المصطلحات وحده لا يحمي الخبر؛ فالجملة تتغير أيضًا بما حولها. لذلك يحتاج الجزء الحساس من المادة إلى مرساة تعيده دائمًا إلى الأصل: الاقتباس مرتبط بالتسجيل أو النص الأول، والمسمى الرسمي مرتبط بوثيقته، والعبارة الدبلوماسية المهمة لا تنتقل من نسخة مترجمة إلى أخرى إذا كان المصدر الأصلي متاحًا. وإذا اختلف محرران في مقابل مصطلح، لا يكون السؤال «أي صياغة تبدو أجمل؟»، بل «أي صياغة تحافظ على الوظيفة التي كانت للكلمة في الأصل؟».

وتستطيع التقنية تسريع هذه المراجعة من دون أن تتولاها وحدها. قبل النشر، يمكن مقارنة العناصر الأكثر حساسية بين النسخ والتنبيه إلى اختلافات في النفي، أو درجة اليقين، أو أسماء الجهات، أو المصطلحات المعتمدة، أو الدلالة التي حملتها الاقتباسات بعد الترجمة. ولا يعني كل اختلاف وجود خطأ؛ فاللغات لا تُكتب بالقوالب نفسها. وظيفة المقارنة أن تجعل الفارق مرئيًا قبل النشر. فإذا كان المحرر يجيد لغة المصدر، يفحصه بنفسه، وإن لم يكن يجيدها تُحال النقطة المختلف عليها إلى من يستطيع الرجوع إلى الأصل، لتحديد ما إذا كان الاختلاف ضرورة لغوية أم تغيرًا في المعنى.

وتظهر المشكلة الحقيقية عندما تصبح الفروق نمطًا. إذا كانت جهة واحدة توصف باسم رسمي في لغة وباسم غير معتمد في أخرى، أو إذا كانت العبارات الحذرة تميل باستمرار إلى أن تصبح أكثر حسمًا عند انتقالها إلى لغة معينة، فهذه لم تعد هفوات مترجمين متفرقة. صار لكل مسار لغوي طريقته الخاصة في تفسير المصدر، ومع الوقت تبدأ المؤسسة نفسها في إنتاج نسخ مختلفة من واقع واحد يفترض أنها تصفه.

القارئ الذي يختار العربية أو الإنجليزية أو الفرنسية لا يتوقع أن يختار معها درجة مختلفة من الحقيقة. من الطبيعي أن تختلف الجملة حتى تبدو سليمة في لغتها، لكن ما لا ينبغي أن يتغير هو مقدار اليقين، وقوة الموقف، وهوية من فعل ماذا، وحدود ما قيل فعلًا. فلا يكفي أن تبدو النسخ الثلاث كأن كل واحدة كُتبت أصلًا بلغتها؛ نجاح الترجمة الصحفية أن يصل القارئ في اللغات الثلاث إلى الحقيقة نفسها، حتى لو وصل إليها بكلمات مختلفة.
      `),
      en: {
        title: 'Three Languages Made Three Truths',
        excerpt: 'The same story can be published in three languages, yet a small shift in certainty or force can leave readers with three different versions of what was supposed to be one position.',
        place: 'Jeddah', tags: ['What the Reader Does Not See','News translation','Languages','Accuracy'],
        body: p(`
An organization may publish the same story in Arabic, English and French at the same moment. The event, image and names have not changed, and even the number of paragraphs may be similar. Yet an Arabic reader may see that a party “called for” an action, a reader in another language may understand that it “urged” it, and a third may encounter wording that makes the position sound more decisive than it was in the original. A difference does not need to be a glaring error to have an effect. Sometimes a dictionary-correct word is enough when it does not carry the same force in context.

That is why journalistic translation does not work like a machine replacing one word with another. When a news story is translated, it enters a new linguistic system with its own ways of expressing certainty and possibility, responsibility and commitment, and the distance between a speaker and what they say. “Commitment” and “pledge” are not identical in every context, just as “urge” and “request” do not necessarily carry the same degree of insistence. The difference may look small when searching for an Arabic equivalent, but it becomes important when it changes the level of certainty, the strength of a request or the extent to which a speaker owns a position. The question is no longer simply whether the translation is understandable. It is whether the reader in the second language received the meaning with the same semantic force it had in the first.

A study published in Journalism, a peer-reviewed academic journal specializing in journalism studies, drew on in-depth interviews conducted by researcher Alicia Wright with Indian journalists in New Delhi in 2018 and 2019 and examined how they handled the move from a spoken Hindi interview to a written English story. It showed that the journalist does more than transfer words. They negotiate what has a clear equivalent, what does not move easily into the other language, and how the material is presented to a new linguistic audience. In that journey from source to reader, meaning can acquire implications that were not present to the same degree in the first language. Another study published in Journalism Studies in 2024 reinforces this editorial nature of translation. Examining the Urdu service of United News of India, it concluded that “news translation” is an important, if contested, component of media work in Indian-language journalism.

These differences become more sensitive in diplomatic and legal coverage. A declared position is not a pledge, a pledge is not a binding decision, and the official name of a body or a legal status is not merely a label that can be replaced by something that sounds linguistically close. If those levels are flattened while moving between languages, the basic facts may remain correct while what they mean changes. The organization is not publishing three lies; it is publishing three unequal versions of a position that was supposed to be one.

Quotation is even more sensitive because readers assume it is the part of the story closest to the speaker’s own voice. Reuters journalistic standards state that translated quotes should read naturally in the new language without becoming stiffly literal while preserving the tone of the original. The agency specifically warns against translating a quotation back into its first language after it has already passed through another outlet in a different language, because the result can move far from what was originally said. Literalness is not a guarantee of accuracy, and fluency is not one either. The wording should change as much as the new language requires without changing the speaker’s tone or the meaning of the statement.

The distance grows when the editor is not translating from the original source. A statement delivered in Arabic may be carried by one organization in English, then a newsroom may use that English version to produce a story in French—or even back in Arabic. Each stage may look reasonable on its own, but the chain adds another intermediary between the reader and the original words. If the source disappears from the editor’s view, it becomes difficult to know whether the phrase in front of them was the speaker’s choice or the previous translator’s. Translation then moves more than language; it carries editorial decisions whose starting point later editors may no longer be able to see.

Artificial intelligence did not create this problem. A skilled human translator can choose an equivalent unsuited to an institutional context, just as an automated tool can produce a grammatically correct sentence while dropping a fine distinction between two concepts. Organizations that deal with sensitive language every day do not rely on individual linguistic knowledge alone. The United Nations uses UNTERM for official terminology alongside computer-assisted translation tools, text alignment systems and document repositories. Its translators and editors research new terminology, verify it against reliable sources and consult specialists before approved terms are stored. The tools support consistency and accuracy, but they do not eliminate the need for human judgment capable of understanding meaning, tone and even deliberate ambiguity in some diplomatic texts.

A newsroom can borrow that logic without becoming an international translation department. Instead of each editor beginning from their own dictionary and memory, the organization can build a living editorial glossary for recurring terms in its coverage: the original expression, the approved equivalent in each language, the context in which it applies, the official source for legal and institutional names, and warnings about alternatives that look similar but change the meaning. When a new usage appears or an official name changes, the same record is updated rather than every translation starting from zero.

Terminology alone, however, cannot protect the story because a sentence is also shaped by what surrounds it. Sensitive parts of a story therefore need an anchor that always points back to the source. A quotation is linked to the recording or first text, an official name to its authoritative document, and an important diplomatic phrase should not travel from one translation to another when the original is available. If two editors disagree over an equivalent, the question is not “Which wording sounds nicer?” but “Which wording preserves the function the word had in the original?”

Technology can accelerate that review without carrying it out alone. Before publication, the most sensitive elements across versions can be compared and differences in negation, degree of certainty, institutional names, approved terminology or the meaning of translated quotations can be flagged. Not every difference is an error; languages are not written from identical templates. The purpose of comparison is to make the difference visible before publication. If the editor knows the source language, they can inspect it directly. If not, the disputed point can be sent to someone who can return to the original and determine whether the variation is a linguistic necessity or a change in meaning.

The deeper problem appears when differences become patterns. If the same institution is consistently described by its official name in one language and an unapproved name in another, or if cautious formulations repeatedly become more decisive when moved into a particular language, these are no longer scattered translator slips. Each linguistic track has developed its own way of interpreting the source, and over time the organization begins producing different versions of a single reality it is supposed to describe.

A reader who chooses Arabic, English or French does not expect to choose a different degree of truth with the language. It is natural for sentences to change so they read properly in each language. What should not change is the level of certainty, the force of a position, the identity of who did what, and the boundaries of what was actually said. It is not enough for all three versions to look as though each was originally written in its own language. Successful journalistic translation means readers in all three languages arrive at the same truth, even if they reach it through different words.
        `)
      }
    },
    {
      slug: 'true-news-that-lied', type: 'article', typeLabel: 'مقال',
      title: 'الخبر الصحيح الذي كذب', date: '2026-08-30', place: 'جدة', author: 'دانه بالجهر',
      image: 'assets/covers/default-article.svg', featured: false, pick: false,
      tags: ['ما لا يراه القارئ', 'التضليل', 'السياق', 'الدقة'],
      excerpt: 'قد تكون كل معلومة في الخبر صحيحة وموثقة، ثم يقود تركيبها القارئ إلى استنتاج لا تسنده الأدلة. المشكلة أحيانًا ليست في الجزئيات، بل في الجسر بينها.',
      seriesSlug: 'what-reader-does-not-see', seriesOrder: 4,
      body: p(`
قد تكون جميع المعلومات الواردة في خبر موثقة، ثم ينتهي قارئه إلى فهم لا تسنده أي واحدة منها. الرقم مأخوذ من جدول رسمي، والتصريح مسجل، والحدث مثبت؛ غير أن الطريقة التي ربطت بينها منحتها دلالة أخرى. قد يقع الانحراف في قاعدة المقارنة، أو زمن الواقعة، أو العلاقة الموحى بها بين حدثين، أو الفعل الذي يسبق الاقتباس.

تمنح أبحاث السلوك اسمًا لأحد أشكال هذا البناء. فقد عرّفت دراسة نشرتها Journal of Personality and Social Psychology، وهي مجلة أكاديمية محكّمة متخصصة في علم النفس الاجتماعي والشخصية، ما يُعرف بمصطلح paltering، أو «المخاتلة بالحقائق»، بأنه الاستخدام النشط لعبارات صحيحة لتكوين انطباع مضلل. تناولت الدراسة هذا السلوك في سياق التفاوض، لا العمل الصحفي، إلا أن آليته تكشف ما لا يصل إليه التدقيق الحرفي وحده؛ إذ يستطيع صاحب النص أن ينتقي من الواقع ما يقود المتلقي نحو استنتاج محدد من دون أن يختلق واقعة. ولهذا ينتقل الفحص من مطابقة الجزئيات بمراجعها إلى مراجعة الجسر الذي عبره القارئ منها إلى النتيجة.

أوضح تطبيق لذلك يظهر في الأرقام. فالزيادة من حالتين إلى ثلاث تساوي خمسين في المئة حسابيًا، مع أن مقدار التغير حالة واحدة. لا يوجد خطأ في العملية، لكن إخفاء القيمة الأساسية يمنح حركة محدودة هيئة قفزة واسعة. ويضع مكتب تنظيم الإحصاءات البريطاني OSR، وهو الجهة المستقلة المسؤولة عن تنظيم الإحصاءات الرسمية في المملكة المتحدة، معيارًا يتجاوز سلامة الحساب: قد تكون العبارة صحيحة بذاتها ثم تصبح مضللة إذا كان الوصف الذي تنقله لا تؤيده الشواهد الإحصائية الأوسع. ويقدم المكتب مثالًا على انخفاض أسعار الفائدة بين مارس وأبريل؛ فمن الدقيق وصف ما جرى خلال الشهرين، لكن إعلان أن «أسعار الفائدة تتراجع» قد يوحي باتجاه عام لا تدعمه المدة الأطول.

وإذا كان العدد الأساسي يضبط حجم التحول، فإن التاريخ يحدد موقع الواقعة من الحاضر. إعادة نشر مخالفة ارتكبتها منشأة قبل خمس سنوات من دون إظهار زمنها قد تجعل أمرًا عولج وانتهى يبدو كأنه يحدث الآن. ويملك ترتيب الأحداث قوة مشابهة؛ فالوفاة بعد تلقي علاج تثبت التعاقب وحده، ولا تقيم علاقة سببية بينهما. وتوضح دراسة منشورة في Science، وهي دورية تنشر أبحاثًا محكّمة من تخصصات علمية متعددة، لماذا لا يمكن الاستهانة بالمواد التي تمر من دون وسم صريح بالتضليل. فقد جمعت بين تجربتين بلغ مجموع المشاركين فيهما 18,725 شخصًا وبيانات التعرض لـ13,206 رابطًا متعلقًا بلقاحات كوفيد على فيسبوك في الولايات المتحدة. وقدّر الباحثون أن التأثير الإجمالي للمحتوى المشكك في سلامة اللقاحات، الذي لم تضع عليه جهات التحقق وسمًا، كان أكبر بنحو 46 مرة من نظيره في المواد التي صنفتها تلك الجهات مضللة؛ ويرجع الفارق بدرجة كبيرة إلى اتساع الوصول، لا إلى قوة كل مشاهدة منفردة. وكانت الأخبار التي أبرزت وفيات نادرة وقعت عقب التطعيم من بين الأكثر مشاهدة. لم يختبر البحث الكيفية التي فهم بها كل متلقٍ هذه الأخبار؛ لذا تقتصر دلالته على ما قدّره الباحثون بشأن نيات التطعيم داخل البيئة المدروسة، ولا تسمح بتعميم استجابة واحدة على بقية الجماهير.

وتستطيع مفردة واحدة توجيه المعنى داخل الجملة بالطريقة نفسها. حين يستبدل المحرر «قال» بـ«اعترف»، لا يغير فعل الإسناد فحسب، بل يضيف إيحاءً بوجود ذنب أو حقيقة حاول صاحب التصريح إخفاءها. لا يعني ذلك أن «اعترف» غير صحيحة دائمًا؛ فالسياق قد يجعلها الوصف الأدق، لكن على المادة الأصلية أن تسند الدرجة التي أضافتها الكلمة. وتحذر المعايير التحريرية لوكالة رويترز الدولية للأنباء من الألفاظ التي تضخم المشهد؛ فما يوصف بـ«تدفق» قد يكون عددًا محدودًا، وما يسمى «قفزة» في سعر سهم ربما لا يتجاوز ارتفاعًا متواضعًا. المطلوب ليس تجريد الأسلوب من الحيوية، وإنما ألا يتجاوز وقع اللفظة حجم الحدث.

ولا تسلك هذه الانحرافات طريقًا واحدًا إلى الجمهور. قد يضخم الكاتب وصفًا لجذب الانتباه، أو تمر مسودة غير ناضجة تحت ضغط السرعة، أو يفشل فريق كامل في اكتشاف خلل إحصائي لا يملك أدوات قراءته. أخلاقيًا، لا يتساوى التعمد مع ضعف الخبرة أو الاستعجال، إلا أن OSR لا يعد القصد أساسًا عمليًا للحكم، لصعوبة إثباته وذاتيته. أما في المؤسسة الصحفية، فتتسع دائرة المحاسبة كلما شارك آخرون في الإنتاج؛ فالكاتب يحرر، والمراجع يدقق، ومسؤول آخر قد يعتمد العنوان، ثم تمنح الوسيلة النسخة اسمها. ولهذا تجعل مدونة منظمة معايير الصحافة المستقلة IPSO، وهي جهة بريطانية مستقلة تشرف على الصحف والمجلات والمواقع الإخبارية المنضوية في نظامها، تطبيق قواعدها مسؤولية المحررين والناشرين، وتطلب منهم ضمان التزام العاملين والمساهمين بها. كل عين إضافية لا توزع الخطأ حتى يختفي، بل تنشئ نقطة جديدة كان يمكن عندها إيقافه.

إذا أخفقت هذه النقاط، لا يبقى الضرر داخل الصفحة. قد تتشوه سمعة شخص، أو تظهر جهة في وضع لا تصنعه الوقائع، أو يتحرك النقاش العام على أساس هش. ويصل الأثر إلى الناشر كذلك؛ فالقارئ لم يختر مؤسسة صحفية كي يعيد فحص الجداول والمناهج والأرشيف بنفسه، بل منحها ثقته لأنها تولت هذه المهمة نيابة عنه. وعندما ينكشف خلل جوهري، لا يكفي أن تختفي العبارة في تعديل صامت. تشترط مدونة IPSO معالجة المعلومات المضللة أو المشوهة ذات الأهمية بسرعة وفي موضع ظاهر يتناسب مع أهميتها، فيما توضح إرشاداتها للمنصات الاجتماعية أن التصحيح ينبغي في العادة أن يصل عبر القناة التي روّجت الادعاء، وأن الإحالة إلى رابط موجود في مكان آخر قد لا تكون كافية. ويكتمل ذلك بسجل علني يبين مضمون التغيير ووقته، مع إشعار مستقل في الحسابات التي دفعت النسخة الأولى إلى التداول. عندها لا يختفي الخطأ من الموقع بينما يظل حيًا في المنشورات والصور المقتطعة.

غير أن التصحيح، مهما اتسع وصوله، يظل لاحقًا للنسخة التي كوّنت الانطباع الأول. لذلك تبدأ المعالجة الأعمق بإعادة تصميم مسار الإنتاج. يمكن أن يطلب نظام إدارة المحتوى، وهو المنصة الداخلية التي تمر عبرها المادة من الكتابة إلى النشر، بيانات إضافية تلقائيًا بحسب ما تتضمنه: عند إدخال نسبة يطلب الأعداد الأصلية والمدة التي يغطيها الرقم وأساس المقارنة وطريقة جمع البيانات؛ وإذا كانت الواقعة قديمة يُطلب تاريخها وحالتها الراهنة؛ وعند الجمع بين حدثين يُلزم الكاتب بتحديد ما إذا كانت الصلة مجرد تزامن، أم ارتباطًا، أم علاقة سبب ونتيجة، وإرفاق ما يبررها؛ أما اللفظ الذي يضيف حكمًا إلى كلام المصدر فيحتاج إلى النص الأصلي الذي يسنده. ويعتمد هذه العناصر محرر مستقل لم يشارك في الصياغة، ويفحص معها العنوان والصورة المصاحبة للرابط عند مشاركته والمنشور الاجتماعي، لأن كلًا منها قد يصل إلى الجمهور منفصلًا عن المتن. ولا تنتقل المادة إلى المرحلة التالية قبل معالجة أي فجوة تكشفها هذه المراجعة.

لكن تعديل النظام الإلكتروني لا يكفي إذا بقيت المهارات والحوافز كما هي. لذلك يُبنى التأهيل المهني على الأخطاء الفعلية التي تكشفها مراجعات كل قسم، بحيث تعالج البرامج نقاط ضعفه المتكررة بدل تقديم دورات عامة منفصلة عن إنتاجه. ويحتاج المراجع في المقابل إلى صلاحية فعلية لإيقاف المادة من دون أن يُعامل قراره بوصفه تعطيلًا للإنتاج. ثم يأتي نظام التقييم؛ فالمؤسسة التي تكافئ السرعة والتفاعل وحدهما تجعل المبالغة ذات عائد مهني. ويُقاس أداء المراجع بما يكتشفه قبل النشر، بينما تُقاس المنظومة بنسبة المواد التي احتاجت إلى تصحيح جوهري بعد النشر، وتكرار أسباب الخلل، ومدى وصول إشعارات التعديل مقارنة بالنسخ الأصلية. ويتولى محرر المعايير، وهو المسؤول عن متابعة تطبيق القواعد التحريرية داخل المؤسسة، تحليل هذه المؤشرات دوريًا، ثم يحول نتائجها إلى تغييرات في قوائم الفحص والصلاحيات والمهارات المطلوبة، بدل أن تنتهي كل واقعة بتنبيه فردي يُنسى عند الخبر التالي.

وقبيل اعتماد النسخة، يبقى اختبار واحد يلخص هذه المنظومة: يكتب المراجع في جملة ما الذي سيفهمه قارئ معقول من المادة، ثم يضع أمامها ما يجيز هذا الفهم من الأدلة. إذا تعذر ذلك، فالمشكلة ليست في جمهور أساء القراءة، بل في صياغة طلبت منه الوصول إلى نتيجة لا يستطيع ناشرها إثباتها. ذلك هو الفرق بين نص اجتاز الإجراءات، ونص استحق ثقة القارئ.
      `),
      en: {
        title: 'The True Story That Lied',
        excerpt: 'Every fact in a story can be accurate and documented while their arrangement leads the reader to a conclusion the evidence does not support. Sometimes the problem is not in the parts, but in the bridge between them.',
        place: 'Jeddah', tags: ['What the Reader Does Not See','Misleading information','Context','Accuracy'],
        body: p(`
Every piece of information in a news story may be documented, yet the reader can finish it with an understanding that none of those facts actually supports. The number comes from an official table, the statement is recorded, and the event is verified, but the way they were connected gives them another meaning. The distortion may lie in the basis of comparison, the timing of the event, the relationship implied between two events, or the verb placed before a quotation.

Behavioral research gives one form of this construction a name. A study published in the Journal of Personality and Social Psychology, a peer-reviewed journal specializing in social and personality psychology, defined “paltering” as the active use of truthful statements to create a misleading impression. The study examined the behavior in negotiation rather than journalism, but its mechanism exposes what literal fact-checking alone may miss. A writer can select true elements of reality in a way that guides the audience toward a particular conclusion without inventing a fact. Verification therefore has to move from matching each fragment to its source to examining the bridge the reader is invited to cross from those fragments to the conclusion.

Numbers offer the clearest example. An increase from two cases to three is mathematically 50 percent even though the absolute change is one case. The calculation is not wrong, but hiding the baseline gives a limited movement the appearance of a large jump. The UK Office for Statistics Regulation (OSR), the independent body responsible for regulating official statistics in the United Kingdom, sets a standard that goes beyond mathematical correctness: a statement can be true in isolation and still mislead if the description it conveys is not supported by the wider statistical evidence. The office gives the example of interest rates falling between March and April. It is accurate to describe what happened over those two months, but saying “interest rates are falling” may imply a broader trend that a longer time frame does not support.

If the baseline controls the scale of change, the date controls where an event sits in relation to the present. Republishing a violation committed by an organization five years ago without making its timing visible can make something that was addressed and concluded appear current. The order of events has similar power. A death after treatment establishes sequence alone; it does not establish causation. A study published in Science, a journal carrying peer-reviewed research across scientific fields, illustrates why material that passes without an explicit misinformation label cannot be dismissed. It combined two experiments with 18,725 participants and exposure data for 13,206 vaccine-related URLs on Facebook in the United States. The researchers estimated that the overall effect of content skeptical of vaccine safety that had not been flagged by fact-checkers was about 46 times greater than content those fact-checkers had labeled misinformation, largely because of its broader reach rather than the power of any single exposure. Stories highlighting rare deaths after vaccination were among the most viewed. The research did not test exactly how every recipient interpreted those stories, so its implications are limited to the researchers’ estimates concerning vaccination intentions in the studied environment and cannot be generalized as one response for all audiences.

A single word can steer meaning inside a sentence in the same way. When an editor replaces “said” with “admitted,” the change does more than vary an attribution verb. It adds an implication of wrongdoing or of a truth the speaker had tried to conceal. “Admitted” is not always inaccurate; context may make it the most precise description. But the original material must support the additional degree of judgment the word carries. Reuters editorial standards warn against language that inflates a scene: what is described as a “flood” may involve a limited number, and what is called a “surge” in a share price may amount to a modest rise. The goal is not to strip writing of energy, but to keep the force of the word from exceeding the scale of the event.

These distortions do not travel to audiences by one route. A writer may exaggerate to attract attention, an immature draft may pass under time pressure, or an entire team may fail to detect a statistical weakness it does not have the tools to read. Ethically, deliberate deception is not equivalent to weak expertise or haste, yet OSR does not treat intention as a practical basis for judgment because it is difficult to prove and inherently subjective. Inside a news organization, accountability expands as more people take part in production. The writer drafts, a reviewer checks, another editor may approve the headline, and the outlet ultimately puts its name on the version. The Independent Press Standards Organisation (IPSO), a UK regulator for participating newspapers, magazines and news sites, therefore makes editors and publishers responsible for applying its code and requires them to ensure that staff and contributors observe it. Every additional pair of eyes does not divide the error until it disappears; it creates another point at which it could have been stopped.

When those points fail, the harm does not stay on the page. A person’s reputation may be distorted, an organization may appear in a situation the facts do not create, and public discussion may move on a weak foundation. The publisher is affected too. A reader did not choose a news organization so they could personally re-check tables, methods and archives. They gave it trust because it took on that work for them. When a material error is exposed, silently removing the wording is not enough. The IPSO code requires significant misleading or distorted information to be corrected promptly and with due prominence. Its social-media guidance explains that a correction should normally reach audiences through the channel that promoted the original claim and that pointing to a link elsewhere may not be sufficient. A public change log stating what changed and when, alongside a separate notice on accounts that pushed the first version into circulation, completes that process. The error then does not disappear from the website while remaining alive in posts and screenshots.

Correction, however widely distributed, still comes after the version that created the first impression. The deeper response therefore begins by redesigning production. A content management system—the internal platform through which material passes from writing to publication—can automatically request additional data based on what a story contains. When a percentage is entered, it can ask for the underlying numbers, the period covered, the basis of comparison and the data-collection method. If an event is old, it can require its date and current status. If two events are connected, the writer can be required to state whether the relationship is mere sequence, correlation or causation and to attach the evidence supporting that classification. A word that adds judgment to a source’s statement can require the original wording that justifies it. An independent editor who did not write the story can approve these elements and also inspect the headline, link-preview image and social post because each may reach the audience separately from the full text. The story does not move to the next stage until gaps revealed by that review are addressed.

Changing the software is not enough if skills and incentives remain unchanged. Professional development therefore needs to be built around the real errors revealed by reviews of each desk, addressing recurring weaknesses rather than offering generic training detached from production. Reviewers, in turn, need genuine authority to stop a story without their decision being treated as an obstacle to output. Then comes evaluation. An organization that rewards speed and engagement alone gives exaggeration a professional return. Reviewers can be assessed by what they catch before publication, while the system can be assessed by the share of stories requiring substantial correction after publication, the recurrence of error types, and the reach of correction notices compared with the original versions. A standards editor—responsible for monitoring the application of editorial rules—can analyze those indicators periodically and turn the findings into changes in checklists, permissions and required skills instead of allowing each incident to end with an individual warning forgotten by the next story.

Before the final version is approved, one test can summarize the whole system. The reviewer writes one sentence describing what a reasonable reader is likely to understand from the story and places beside it the evidence that permits that understanding. If that cannot be done, the problem is not an audience that read badly. It is a piece of writing that asked the audience to reach a conclusion its publisher cannot prove. That is the difference between a text that passed the procedures and a text that earned the reader’s trust.
        `)
      }
    },
    {
      slug: 'headline-stole-story', type: 'article', typeLabel: 'مقال',
      title: 'العنوان سرق الخبر', date: '2026-08-30', place: 'جدة', author: 'دانه بالجهر',
      image: 'assets/covers/default-article.svg', featured: false, pick: false,
      tags: ['ما لا يراه القارئ', 'العناوين', 'التحرير', 'سلوك الجمهور'],
      excerpt: 'العنوان لا يكتفي بتسمية الحدث؛ قد يصنع إطارًا ذهنيًا يسبق المتن ويمنح بعض عناصره وزنًا أكبر قبل أن يبدأ القارئ القراءة.',
      seriesSlug: 'what-reader-does-not-see', seriesOrder: 5,
      body: p(`
قد يضع الصحفي النقطة الأخيرة وهو يظن أن مادته قالت ما أراد، بينما يكون القارئ قد تلقى قولًا آخر قبل أن يبدأ. فالجملة الموضوعة أعلاها لا تكتفي بتسمية الحدث؛ إنها تحدد زاوية الدخول إليه، وتمنح بعض عناصره وزنًا أكبر، وتقترح منذ اللحظة الأولى من يستحق اللوم أو التعاطف وما الذي ينبغي تذكره. وإذا استقر هذا البناء مبكرًا، فقد يتحول المتن من مصدر للمعرفة إلى شرح يحاول اللحاق بصورة اكتملت قبله. عندها لا يعود العنوان بابًا للخبر، بل يصبح منافسًا له على المعنى.

تكشف دراسة محكّمة في Journal of Experimental Psychology: Applied، وهي مجلة متخصصة في علم النفس التطبيقي، أن أثر تلك البداية لا ينتهي بمجرد فتح المادة. عرض الباحثون نصوصًا حملت عناوين تبرز جانبًا ثانويًا بدل الفكرة الأساسية، فغيّرت ما تذكره المشاركون والاستنتاجات التي بنوها ونواياهم السلوكية، رغم قراءتهم المحتوى كاملًا. عملت الصياغة الأولى كإطار ذهني وجّه معالجة المعلومات التالية، وظل تحديث الصورة التي صنعتها صعبًا حتى بعد ظهور التفاصيل الأوسع. لذلك قد يرى الإنسان ما يصحح المبالغة من دون أن يمنحه القوة نفسها التي امتلكها الانطباع السابق.

يضع ذلك المسؤوليتين في موضعهما الصحيح. من يريد إصدار حكم أو تداول معلومة مطالب بالاطلاع على أصلها، لأن العنوان وحده لا يمنحه إحاطة كافية. وفي المقابل لا يجوز للوسيلة أن تجعل الدقة مكافأة لا يحصل عليها إلا من أكمل القراءة؛ فالمباشرة والوضوح في الخبر ليستا نقيضًا للجاذبية، بل حدًا يمنع العبارة المختصرة من قول شيء يحتاج المتن لاحقًا إلى تقييده أو تصحيحه. يستطيع المحرر اختيار المدخل الأقوى، لكنه لا يملك توسيع الواقعة أو نقل مركزها إلى تفصيل أكثر إثارة مع تحميل الجمهور مسؤولية إصلاح ما فهمه.

اتسعت سلطة هذه الجملة عندما خرجت المادة من الصفحة التي كانت تمنحها سياقها. في الصحيفة المطبوعة يظهر العنوان داخل قسم وعدد وترتيب تحريري متكامل، أما اليوم فقد يصل منفردًا في نتيجة بحث، أو معاينة على منصة اجتماعية، أو إشعار على شاشة مقفلة. يسمي الباحثون هذا التحول «تفكيك الحزمة الصحفية»، أي انتقال المنافسة من بيع إصدار كامل إلى تنافس كل موضوع وحده على الانتباه. وفحص بحث منشور في Humanities and Social Sciences Communications، وهي دورية أكاديمية في العلوم الإنسانية والاجتماعية، قرابة أربعين مليون عنوان إنجليزي خلال عقدين، ورصد ازدياد الطول والسلبية والأسئلة والضمائر وبناء الجمل المكتملة عبر مؤسسات مختلفة. لا تثبت تلك البيانات أن البيئة الرقمية سببت كل تغير، لكنها توضح أن شكل التقديم تبدل بالتزامن مع تحول كل مادة إلى منتج قائم بذاته.

ما إن أصبح الدخول قابلًا للعد حتى انتقل الاختيار من الحدس التحريري وحده إلى التجربة المباشرة. يتيح اختبار A/B، وهو توزيع صيغ متعددة للموضوع نفسه على مجموعات متقاربة ومقارنة أدائها، معرفة أيها يدفع عددًا أكبر إلى الضغط. وحلل بحث مسجّل منشور في Nature Human Behaviour، والمقصود به دراسة خضعت أسئلتها وخطتها للتحكيم قبل الاطلاع على النتائج، 22,743 تجربة عشوائية أجراها موقع Upworthy، وهو ناشر رقمي أميركي اشتهر بصناعة المحتوى واسع الانتشار. شملت البيانات نحو 105 آلاف بديل، و5.7 ملايين نقرة، وأكثر من 370 مليون ظهور، وكان الموقع يطلب من محرريه عادة اقتراح 25 خيارًا للمادة الواحدة. وأظهر التحليل أن إضافة كلمة سلبية إلى صيغة متوسطة تقارب خمس عشرة كلمة رفعت معدل النقر إلى الظهور بنحو 2.3 في المئة؛ ويقيس هذا المعدل نسبة النقرات إلى إجمالي مرات ظهور الرابط. لا تسمح عينة مأخوذة من جهة واحدة بتعميم الرقم على اللغات وغرف الأخبار كافة، كما قد تكون اللهجة القاتمة وصفًا أمينًا لواقعة قاتمة. القيمة الأهم أن المفردة وحدها استطاعت تغيير الإقبال على محتوى ثابت، فصار للتهويل المحتمل عائد مرئي تسجله لوحة الأداء فورًا.

هنا يظهر قصور المقياس: إنه يعرف من ضغط، ولا يعرف ماذا فهم. قد تفوز عبارة لأنها وسّعت نطاق الأزمة، أو أوحت بنتيجة محسومة، أو رفعت تفصيلًا فرعيًا إلى مرتبة الحدث، فتسجل الأداة نجاحًا كاملًا ما دام الزائر انتقل إلى المنصة الأصلية. أما مطابقة التوقع الذي صنعه التقديم لما أثبته النص، فلا تدخل في الحساب. وبذلك لا تفرض التقنية التضليل مباشرة، لكنها تمنح خاصية واحدة قابلة للقياس سلطة الترجيح على خصائص لا تظهر في الأرقام.

تنتقل تلك السلطة إلى الأشخاص الذين يديرون النظام، وتترسخ إذا دخلت مخرجاته في تقييمهم. فقد وثق بحث نوعي في مجلة Media and Communication، أي دراسة تعتمد على المقابلات وتحليل الخبرات بدل القياس الكمي، ممارسات الاختبار لدى عينة صغيرة من العاملين في مؤسسات أميركية. كانت البدائل تُكتب غالبًا بواسطة الصحفيين والمحررين، في حين يتولى مختصون بنمو الجمهور تشغيل الأداة وتفسير حصيلتها، وقد تعتمد بعض الأنظمة الصيغة الفائزة تلقائيًا عند اكتمال التجربة. احتفظت هيئة التحرير بحق رفض ما تراه غير دقيق أو غير ممثل للفكرة، إلا أن امتلاك وسيلة القياس منح القائمين عليها حضورًا فعليًا في تحديد اللغة المنشورة. وتضيف حالة ميدانية عن «ثقافة العمل الإخباري المدفوعة بالبيانات»، أي البيئة التي تستند فيها القرارات والتقييمات إلى مؤشرات الجمهور، أن الأرقام دخلت الإرشاد الوظيفي والمكافآت داخل المؤسسة الاسكندنافية التي بحثتها، فنال التغليف والتوقيت اهتمامًا ظاهرًا، بينما عوملت جهود البحث والتحقق كواجبات مفترضة. لا تصف الحالتان قطاع الإعلام كله، لكنهما تكشفان كيف ينتقل الدليل الرقمي من مساعدة الاجتهاد المهني إلى إعادة ترتيب ما تعدّه غرفة الأخبار نجاحًا وما تكافئ العاملين عليه.

ويظهر أثر آخر حين يُعامل الفائز كأنه صالح لكل سياق. أشار المشاركون أنفسهم إلى أن قيود نظام إدارة المحتوى، وهو البرنامج الذي تُكتب الأخبار وتُنظم وتُنشر من خلاله، قد تدفع إلى استخدام صياغة موحدة في الواجهة الرئيسية والبحث والمنصات والإشعارات، أو نقل نتيجة اختبار أجري في قناة إلى بقية القنوات. غير أن عبارة ترافقها صورة ومقدمة ليست كالتي تظهر وحدها على هاتف، وما ينجح وسط موقع يعرفه الزائر قد يتغير معناه حين يُقتطع من محيطه ويظهر بجوار منشورات أخرى. يصبح النسخ الآلي في هذه الحالة قرارًا تحريريًا غير معلن، لأنه يفترض أن كل بيئة تقدم القدر نفسه من السياق.

في الجهة الأخرى، لا يقف المستخدم عند الاستقبال. تناولت سلسلة منشورة في Journal of Consumer Psychology، وهي مجلة تدرس أثر العمليات النفسية في السلوك الاستهلاكي، ما يحدث عندما يشارك الفرد محتوى لم يقرأه. رصدت إحدى الدراسات علاقة بين المشاركة وارتفاع «المعرفة الذاتية»، أي مقدار ما يظنه الإنسان عن علمه بالموضوع، فيما أثبتت تجارب أخرى أن فعل النشر نفسه قد يرفع هذا الشعور من دون زيادة مساوية في المعلومات الفعلية. ورأى الباحثون أن تقديم المحتوى أمام الآخرين يرسل إشارة بالخبرة، وقد يدمج صاحب الحساب هذه الصورة العامة في تقديره لنفسه. لم يقتصر البحث على العناوين الصحفية، ولذلك لا يثبت أن كل مشاركة تولد وهمًا بالمعرفة، إلا أنه يشرح كيف يتحول الاكتفاء بالجملة الظاهرة من نقص في الاطلاع إلى ثقة تنتقل مع المنشور إلى الآخرين.

لهذا لا تكفي وصية تطلب من الصحفي كتابة عنوان أفضل، لأن البنية القائمة قادرة على مكافأة الخيار المعيب وإثبات تفوقه بمؤشر فوري. يبدأ الإصلاح بالفصل بين صلاحيتين لا يجوز دمجهما: يحدد التحرير ما يمكن نشره، ويأتي اختبار الأداء لاحقًا بين البدائل التي اجتازت ذلك الحد فقط. يُرفق كل مقترح بجملة تحدد ما يرجح أن يفهمه من يراه منفردًا، ويقارن محرر مستقل هذا الاستنتاج بما تثبته المادة. ويقوم الفحص على «التكافؤ الدلالي»، أي اختلاف الكلمات مع بقاء الدلالة الأساسية واحدة. ما يضخم النتيجة أو يبدل موقعها يُستبعد سلفًا، فلا تستطيع كثرة الضغط إعادة صيغة رفضتها المراجعة إلى الواجهة.

بعد اجتياز البوابة التحريرية، يتغير تعريف الفوز نفسه. إلى جانب معدل النقر إلى الظهور، تعرض المؤسسة الخيارات على عينة صغيرة متجددة، وتسأل أفرادها عما حدث وفق ما فهموه، وتقارن الإجابات بالنتيجة التي يثبتها النص. ويمكنها تسمية الحصيلة داخليًا «معدل انحراف الفهم»، أي نسبة ابتعاد الاستنتاجات المتكررة عن المعنى الموثق. فإذا اجتذب أحد البدائل زيارات أكثر وترك تصورًا أوسع أو أشد مما تسمح به الوقائع، يفشل مهما بدا متفوقًا تجاريًا. مدة البقاء وإكمال القراءة تكشفان السلوك، لكنهما لا تقيسان ما تعلّمه الجمهور؛ لذلك يملأ هذا الفحص الفراغ الذي لا تراه تحليلات الزيارات.

وتحتاج الوقاية تقنيًا إلى إزالة افتراض الصيغة العامة. يُخصص نظام النشر حقولًا مستقلة للموقع ومحرك البحث والمنشور الاجتماعي والإشعار، مع مراجعة كل صيغة كما سيشاهدها جمهورها فعلًا. ويُوقف التفعيل التلقائي للصيغة الأعلى أداءً في المواد الصحية والأمنية والقضائية وما يمس السمعة حتى يعتمدها محرر بعد انتهاء التجربة. كما يُحفظ سجل داخلي يبين الخيارات المعروضة، والمقياس الذي رجّح بينها، وصاحب القرار النهائي؛ فيستطيع محرر المعايير رصد الأقسام أو المفردات أو أنواع الأخبار التي يتكرر فيها الانحراف، لتُعدّل الصلاحيات والتدريب والحوافز بدل معالجة الوقائع كعثرات منفصلة.

كلما قصرت المساحة زادت مسؤولية الاختيار، لأن كل كلمة تحمل حصة أكبر من الدلالة، وأي انحراف فيها يغيّر الرسالة كلها. العنوان ليس وعدًا بأن الحقيقة موجودة في الأسفل، بل أول جزء منها. وإذا احتاج الناشر بعد الانتشار إلى القول إن المقصود لا يظهر إلا داخل التفاصيل، فقد أقر بأن المتن لم يقد المعنى منذ البداية، وأن العنوان سبقه وسرق الخبر.
      `),
      en: {
        title: 'The Headline Stole the Story',
        excerpt: 'A headline does more than name an event. It can create a mental frame before the article begins and give some elements greater weight before the reader reaches the body.',
        place: 'Jeddah', tags: ['What the Reader Does Not See','Headlines','Editing','Audience behavior'],
        body: p(`
A journalist may place the final full stop believing the story says exactly what they intended, while the reader has already received a different message before they begin. The line above the story does more than name the event. It sets the angle of entry, gives some elements more weight, and suggests from the first moment who deserves blame or sympathy and what should be remembered. If that frame settles early, the body can shift from being the source of knowledge to an explanation trying to catch up with an image already completed. The headline then stops being a doorway into the story and becomes its competitor for meaning.

A peer-reviewed study in the Journal of Experimental Psychology: Applied, a journal specializing in applied psychology, shows that the effect of that beginning does not end when the article is opened. Researchers presented texts with headlines that emphasized a secondary aspect instead of the central idea. Those headlines changed what participants remembered, the inferences they made and their behavioral intentions even though they read the full content. The initial wording acted as a mental frame that guided the processing of what followed, and updating the picture it created remained difficult even after broader details appeared. A person can therefore see information that corrects an exaggeration without giving that correction the same force the first impression already acquired.

This puts two responsibilities in their proper places. Anyone who wants to make a judgment or circulate information has a responsibility to look at the original material because a headline alone does not provide enough context. At the same time, a news organization cannot make accuracy a reward available only to those who finish the article. Directness and clarity in news are not the opposite of appeal; they are the boundary that prevents a short line from saying something the body later has to qualify or correct. An editor can choose the strongest entry point, but cannot enlarge the event or move its center to a more dramatic detail and then make the audience responsible for repairing what it understood.

The power of that line expanded when the story left the page that once supplied its context. In print, a headline appears inside a section, an edition and an editorial hierarchy. Today it may arrive alone in a search result, a social preview or a notification on a locked screen. Researchers describe this shift as the “unbundling” of journalism: competition moves from selling an entire edition to having each story compete individually for attention. Research published in Humanities and Social Sciences Communications, an academic journal in the humanities and social sciences, examined nearly forty million English-language headlines across two decades and found increases in length, negativity, questions, pronouns and complete-sentence construction across different organizations. The data do not prove that the digital environment caused every change, but they show that presentation changed alongside the transformation of every story into a product that stands on its own.

Once entry could be counted, selection moved beyond editorial intuition into direct experimentation. A/B testing—distributing several versions of the same item to comparable groups and comparing their performance—shows which version persuades more people to click. A preregistered study published in Nature Human Behaviour analyzed 22,743 randomized experiments conducted by Upworthy, a U.S. digital publisher known for highly shareable content. The dataset included roughly 105,000 variants, 5.7 million clicks and more than 370 million impressions, while the site typically asked editors to propose 25 options for one story. The analysis found that adding one negative word to an average headline of about fifteen words increased click-through rate by roughly 2.3 percent. That rate measures clicks as a share of total link impressions. A sample from one publisher cannot support generalization across languages and newsrooms, and dark wording can of course accurately describe a dark event. The more important point is that a single word changed demand for otherwise fixed content, giving potential exaggeration a visible return that a performance dashboard could record immediately.

Here the limitation of the metric appears: it knows who clicked, but not what they understood. A version may win because it widened the scale of a crisis, implied that an outcome was settled, or elevated a secondary detail into the event itself. The tool records success as long as the visitor reaches the original platform. Whether the expectation created by the presentation matches what the text actually proves is not part of the calculation. Technology therefore does not directly impose deception, but it gives one measurable property the power to outweigh properties that do not appear in the numbers.

That power moves to the people who operate the system and becomes stronger if its outputs enter their evaluation. Qualitative research in Media and Communication, based on interviews and analysis of professional experience rather than quantitative measurement, documented testing practices among a small sample of workers at U.S. organizations. Variants were usually written by journalists and editors, while audience-development specialists operated the tool and interpreted its results, and some systems could automatically adopt the winning version when the test ended. Editorial staff retained the right to reject wording they considered inaccurate or unrepresentative, yet control of the measurement system gave those managing it a real presence in determining published language. A field study of “data-driven news work culture”—an environment in which decisions and evaluations rely on audience metrics—adds that numbers entered coaching and reward systems in the Scandinavian organization it examined. Packaging and timing received visible attention while research and verification were treated as assumed duties. Neither case describes the entire news industry, but together they show how digital evidence can move from assisting professional judgment to rearranging what the newsroom defines as success and what it rewards.

Another effect appears when the winner is treated as suitable for every context. Participants in the same research noted that content-management-system constraints can encourage organizations to use one formulation on the homepage, in search, on platforms and in notifications, or to carry the result of a test conducted in one channel across the rest. Yet a line accompanied by an image and introduction is not the same as a line appearing alone on a phone, and wording that succeeds inside a familiar site can change meaning when removed from that context and placed beside unrelated posts. Automated copying becomes an unspoken editorial decision because it assumes that every environment supplies the same amount of context.

The user is not merely a passive recipient either. A series of studies published in the Journal of Consumer Psychology, a journal examining psychological processes in consumer behavior, investigated what happens when people share content they have not read. One study found an association between sharing and increased “subjective knowledge”—how much people believe they know about a topic—while other experiments found that the act of posting itself could raise that feeling without an equivalent increase in actual information. The researchers argued that presenting content to others can signal expertise and that account holders may incorporate that public image into their self-assessment. The research was not limited to news headlines, so it does not show that every share produces an illusion of knowledge. It does help explain how stopping at the visible line can move from incomplete exposure to confidence that travels with the post to others.

That is why simply telling journalists to write better headlines is not enough. The structure itself can reward a defective option and prove its superiority through an immediate metric. Reform begins by separating two powers that should not be merged. Editorial review determines what is publishable; performance testing comes later and only among alternatives that have already passed that threshold. Each proposed version is accompanied by a sentence stating what a person who sees it alone is likely to understand, and an independent editor compares that inference with what the story proves. The test is one of “semantic equivalence”: the words may differ while the core meaning remains the same. Anything that enlarges the outcome or relocates its center is rejected in advance, so high click volume cannot return a version the editorial review has ruled out.

After that editorial gate is passed, the definition of winning changes. Alongside click-through rate, the organization can show variants to a small, renewing sample and ask participants what happened according to what they understood, then compare their answers with the outcome established by the text. Internally, it could call the result an “understanding deviation rate”: the proportion by which repeated inferences depart from the documented meaning. If one version attracts more visits but leaves an impression broader or more severe than the facts allow, it fails no matter how commercially strong it appears. Dwell time and completion reveal behavior, but they do not measure what the audience learned; this test fills the gap traffic analytics cannot see.

Prevention also requires removing the technical assumption that one formulation fits everywhere. The publishing system can provide separate fields for the website, search engine, social post and notification, with each version reviewed as its audience will actually see it. Automatic activation of the highest-performing version can be disabled for health, security, court and reputationally sensitive stories until an editor approves it after the test. An internal record can preserve the options shown, the metric that ranked them and the person who made the final decision. A standards editor can then detect desks, words or story types in which meaning repeatedly drifts and adjust permissions, training and incentives instead of treating each case as an isolated stumble.

The shorter the space, the greater the responsibility of selection, because every word carries a larger share of the meaning and any distortion changes the whole message. A headline is not a promise that the truth is somewhere below; it is the first part of that truth. If, after a story spreads, a publisher has to say that the intended meaning appears only inside the details, it has acknowledged that the body did not lead the meaning from the start—and that the headline got there first and stole the story.
        `)
      }
    }
  ];

  window.BUNDLED_SERIES = series;
  window.SERIES_ARTICLES = articles;
  window.ARTICLES = [...(window.ARTICLES || []), ...articles.filter(a => !(window.ARTICLES || []).some(x => x.slug === a.slug))];
  window.ARTICLE_TRANSLATIONS_EN = window.ARTICLE_TRANSLATIONS_EN || {};
  for (const a of articles) if (a.en) window.ARTICLE_TRANSLATIONS_EN[a.slug] = a.en;
})();
