(() => {
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const copy={
  ar:{name:'دانه بالجهر',portfolio:'منصة تحريرية',home:'الرئيسية',archive:'أعمال دانه',title:'كل جديد، يوصل لك.',deck:'سجلي بريدك مرة واحدة، وبيوصلك تنبيه تلقائي وقت ما تنزل مادة جديدة تناسب اهتماماتك.',emailKicker:'الخيار المضمون',emailTitle:'التنبيه بالبريد',emailDeck:'يشتغل على الجوال والكمبيوتر، وما يحتاج تثبيت ولا إذن من المتصفح.',emailLabel:'البريد الإلكتروني',topicsTitle:'وش يهمك؟',all:'كل الجديد',tech:'تقنية',careers:'سوق العمل',sports:'رياضة',arts:'فنون وثقافة',society:'مجتمع',economy:'اقتصاد',media:'إعلام',entertainment:'ترفيه',consent:'أوافق على استلام تحديثات دانه، وأقدر ألغي الاشتراك بأي وقت.',submit:'فعّلي التنبيه البريدي',saving:'جارٍ تفعيل التنبيه…',success:'تم الاشتراك ✓ أرسلنا لك رسالة تأكيد، ومن الآن أي مادة جديدة ضمن اهتماماتك توصلك تلقائيًا.',stored:'تم حفظ الاشتراك ✓',error:'تعذر الاشتراك الآن. جربي مرة ثانية.',pushKicker:'اختياري',pushTitle:'تنبيه الجوال',pushDeck:'فعّليه كخيار إضافي. على الآيفون لازم تفتحين الموقع من Safari وتضيفينه للشاشة الرئيسية أولًا.',pushButton:'فعّلي تنبيه الجوال',pushOn:'تنبيه الجوال مفعّل ✓',pushBlocked:'ما قدرنا نفعّل تنبيه الجوال هنا. استخدمي البريد؛ هو الخيار المضمون.',promiseKicker:'وش يصلك؟',promiseOne:'تنبيه عند نشر مادة جديدة فقط.',promiseTwo:'اختيارات آمنة ومهمة للفئة المستهدفة.',promiseThree:'بدون رسائل دعائية أو إزعاج.',privacy:'الخصوصية'},
  en:{name:'Dana Baljher',portfolio:'Editorial Newsroom',home:'Home',archive:"Dana's work",title:'Every new story, delivered.',deck:'Enter your email once and receive an automatic alert whenever a new story matching your interests is published.',emailKicker:'RELIABLE OPTION',emailTitle:'Email alerts',emailDeck:'Works on phones and computers with no installation or browser permission.',emailLabel:'Email address',topicsTitle:'What interests you?',all:'All stories',tech:'Technology',careers:'Careers',sports:'Sports',arts:'Arts & Culture',society:'Society',economy:'Economy',media:'Media',entertainment:'Entertainment',consent:'I agree to receive Dana’s updates and can unsubscribe at any time.',submit:'Enable email alerts',saving:'Enabling alerts…',success:'Subscribed ✓ A confirmation email was sent. New stories matching your interests will now arrive automatically.',stored:'Subscription saved ✓',error:'Could not subscribe right now. Please try again.',pushKicker:'OPTIONAL',pushTitle:'Phone notifications',pushDeck:'Enable this as an extra option. On iPhone, first open the site in Safari and add it to your Home Screen.',pushButton:'Enable phone alerts',pushOn:'Phone alerts are on ✓',pushBlocked:'Phone alerts could not be enabled here. Email is the reliable option.',promiseKicker:'WHAT YOU GET',promiseOne:'An alert only when a new story is published.',promiseTwo:'Safe, relevant picks for the target audience.',promiseThree:'No advertising or spam.',privacy:'Privacy'}
};
let lang=new URLSearchParams(location.search).get('lang')||localStorage.getItem('dana-lang')||'ar';if(!copy[lang])lang='ar';
let theme=localStorage.getItem('dana-theme')||'light';
const swReady=('serviceWorker' in navigator)?navigator.serviceWorker.register('./service-worker.js?v=18.11',{updateViaCache:'none'}).then(reg=>{reg.update().catch(()=>{});return navigator.serviceWorker.ready}).catch(()=>null):Promise.resolve(null);
function paint(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.documentElement.dataset.theme=theme;$$('[data-sub]').forEach(el=>{const key=el.dataset.sub;if(copy[lang][key])el.textContent=copy[lang][key]});document.title=lang==='ar'?'نبّهني عند النشر | دانه بالجهر':'Publication alerts | Dana Baljher';$('#subTheme').textContent=theme==='light'?'◐':'○'}
$('#subLang').onclick=()=>{lang=lang==='ar'?'en':'ar';localStorage.setItem('dana-lang',lang);paint()};$('#subTheme').onclick=()=>{theme=theme==='light'?'dark':'light';localStorage.setItem('dana-theme',theme);paint()};
const form=$('[data-subscribe-form]'),status=$('[data-subscribe-status]'),all=form.querySelector('input[value="all"]'),topics=$$('input[name="topic"]',form);
topics.forEach(ch=>{ch.onchange=()=>{if(ch===all&&ch.checked)topics.filter(x=>x!==all).forEach(x=>x.checked=false);if(ch!==all&&ch.checked)all.checked=false;if(!topics.some(x=>x.checked))all.checked=true}});
form.onsubmit=async e=>{e.preventDefault();const btn=form.querySelector('button[type="submit"]'),fd=new FormData(form),email=String(fd.get('email')||'').trim(),selected=$$('input[name="topic"]:checked',form).map(x=>x.value);btn.disabled=true;status.className='subscription-status';status.textContent=copy[lang].saving;try{if(!window.DanaBackend)throw new Error('Backend unavailable');const r=await window.DanaBackend.newsletterSubscribe(email,selected,lang);status.classList.add('success');status.textContent=r.emailConfigured?copy[lang].success:copy[lang].stored;form.reset();all.checked=true}catch(err){status.classList.add('error');status.textContent=(err&&err.message)||copy[lang].error}finally{btn.disabled=false}};
const pushBtn=$('#enablePush'),pushStatus=$('#pushStatus');async function paintPush(){try{await swReady;const st=await window.DanaBackend.pushStatus();if(st.enabled){pushBtn.textContent=copy[lang].pushOn;pushBtn.disabled=true}}catch{}}
pushBtn.onclick=async()=>{pushBtn.disabled=true;pushStatus.textContent='';try{await swReady;await window.DanaBackend.enablePush(['all']);pushBtn.textContent=copy[lang].pushOn}catch{pushBtn.disabled=false;pushStatus.textContent=copy[lang].pushBlocked}};
paint();paintPush();
})();
